export interface Cie10Code {
  code: string
  desc: string
}

export const CIE10_CODES: Cie10Code[] = [
  // ── A: Enfermedades infecciosas intestinales ──────────────────────────────
  { code: 'A00', desc: 'Cólera' },
  { code: 'A00.0', desc: 'Cólera debida a Vibrio cholerae 01, biotipo cholerae' },
  { code: 'A00.1', desc: 'Cólera debida a Vibrio cholerae 01, biotipo El Tor' },
  { code: 'A01', desc: 'Fiebres tifoidea y paratifoidea' },
  { code: 'A01.0', desc: 'Fiebre tifoidea' },
  { code: 'A01.1', desc: 'Fiebre paratifoidea A' },
  { code: 'A02', desc: 'Otras infecciones debidas a Salmonella' },
  { code: 'A02.0', desc: 'Enteritis debida a Salmonella' },
  { code: 'A03', desc: 'Shigelosis' },
  { code: 'A04', desc: 'Otras infecciones intestinales bacterianas' },
  { code: 'A04.0', desc: 'Infección debida a Escherichia coli enteropatógena' },
  { code: 'A04.4', desc: 'Otras infecciones intestinales por Escherichia coli' },
  { code: 'A05', desc: 'Otras intoxicaciones alimentarias bacterianas' },
  { code: 'A06', desc: 'Amebiasis' },
  { code: 'A06.0', desc: 'Disentería amebiana aguda' },
  { code: 'A07', desc: 'Otras enfermedades intestinales debidas a protozoarios' },
  { code: 'A07.1', desc: 'Giardiasis (lambliasis)' },
  { code: 'A08', desc: 'Infecciones intestinales virales' },
  { code: 'A08.0', desc: 'Enteritis debida a rotavirus' },
  { code: 'A09', desc: 'Gastroenteritis y colitis de origen no especificado' },
  // ── A15-A19: Tuberculosis ──────────────────────────────────────────────────
  { code: 'A15', desc: 'Tuberculosis respiratoria, confirmada bacteriológicamente' },
  { code: 'A15.0', desc: 'Tuberculosis del pulmón, confirmada por hallazgo microscópico' },
  { code: 'A16', desc: 'Tuberculosis respiratoria, sin confirmación bacteriológica' },
  { code: 'A16.0', desc: 'Tuberculosis pulmonar, negatividad bacteriológica e histológica' },
  { code: 'A17', desc: 'Tuberculosis del sistema nervioso' },
  { code: 'A18', desc: 'Tuberculosis de otros órganos' },
  { code: 'A19', desc: 'Tuberculosis miliar' },
  // ── A30-A49: Otras enfermedades bacterianas ────────────────────────────────
  { code: 'A30', desc: 'Lepra' },
  { code: 'A36', desc: 'Difteria' },
  { code: 'A37', desc: 'Tos ferina (pertussis)' },
  { code: 'A38', desc: 'Escarlatina' },
  { code: 'A39', desc: 'Infección meningocócica' },
  { code: 'A40', desc: 'Septicemia estreptocócica' },
  { code: 'A41', desc: 'Otras septicemias' },
  { code: 'A41.5', desc: 'Septicemia debida a otros organismos gramnegativos' },
  { code: 'A41.9', desc: 'Septicemia, no especificada' },
  { code: 'A46', desc: 'Erisipela' },
  { code: 'A49', desc: 'Infección bacteriana de sitio no especificado' },
  // ── A50-A64: Infecciones de transmisión sexual ─────────────────────────────
  { code: 'A50', desc: 'Sífilis congénita' },
  { code: 'A51', desc: 'Sífilis temprana' },
  { code: 'A51.0', desc: 'Sífilis genital primaria' },
  { code: 'A52', desc: 'Sífilis tardía' },
  { code: 'A53', desc: 'Otras sífilis y las no especificadas' },
  { code: 'A54', desc: 'Infección gonocócica' },
  { code: 'A56', desc: 'Otras enfermedades de transmisión sexual por Chlamydia' },
  { code: 'A59', desc: 'Tricomoniasis' },
  { code: 'A60', desc: 'Infección anogenital debida a virus del herpes (herpes simplex)' },
  { code: 'A63', desc: 'Otras enfermedades de transmisión predominantemente sexual' },
  // ── A77-A99: Arbovirosis ──────────────────────────────────────────────────
  { code: 'A90', desc: 'Fiebre del dengue (dengue clásico)' },
  { code: 'A91', desc: 'Fiebre del dengue hemorrágico' },
  { code: 'A92', desc: 'Otras fiebres virales transmitidas por mosquito' },
  { code: 'A92.0', desc: 'Infección por virus chikungunya' },
  { code: 'A92.5', desc: 'Fiebre del Zika' },
  { code: 'A95', desc: 'Fiebre amarilla' },
  { code: 'A98', desc: 'Otras fiebres hemorrágicas virales' },
  // ── B00-B09: Infecciones virales ──────────────────────────────────────────
  { code: 'B00', desc: 'Infecciones debidas a herpesvirus' },
  { code: 'B00.0', desc: 'Eczema herpético' },
  { code: 'B00.1', desc: 'Dermatitis vesicular herpética' },
  { code: 'B00.2', desc: 'Gingivoestomatitis herpética' },
  { code: 'B01', desc: 'Varicela' },
  { code: 'B01.9', desc: 'Varicela sin complicaciones' },
  { code: 'B02', desc: 'Herpes zóster' },
  { code: 'B02.9', desc: 'Herpes zóster sin complicaciones' },
  { code: 'B05', desc: 'Sarampión' },
  { code: 'B06', desc: 'Rubéola' },
  { code: 'B07', desc: 'Verrugas víricas' },
  { code: 'B08', desc: 'Otras infecciones víricas caracterizadas por lesiones cutáneas y mucosas' },
  // ── B15-B19: Hepatitis víricas ─────────────────────────────────────────────
  { code: 'B15', desc: 'Hepatitis aguda tipo A' },
  { code: 'B15.0', desc: 'Hepatitis A con coma hepático' },
  { code: 'B15.9', desc: 'Hepatitis A sin coma hepático' },
  { code: 'B16', desc: 'Hepatitis aguda tipo B' },
  { code: 'B16.9', desc: 'Hepatitis B aguda sin virus delta y sin coma hepático' },
  { code: 'B17', desc: 'Otras hepatitis víricas agudas' },
  { code: 'B18', desc: 'Hepatitis vírica crónica' },
  { code: 'B18.1', desc: 'Hepatitis B crónica sin virus delta' },
  { code: 'B18.2', desc: 'Hepatitis C crónica' },
  { code: 'B19', desc: 'Hepatitis vírica, sin otra especificación' },
  // ── B20-B24: HIV ──────────────────────────────────────────────────────────
  { code: 'B20', desc: 'Enfermedad por VIH resultante en enfermedades infecciosas y parasitarias' },
  { code: 'B20.0', desc: 'Enfermedad por VIH resultante en infección por micobacterias' },
  { code: 'B21', desc: 'Enfermedad por VIH resultante en tumores malignos' },
  { code: 'B23', desc: 'Enfermedad por VIH resultante en otras afecciones' },
  { code: 'B24', desc: 'Enfermedad por VIH, sin otra especificación' },
  // ── B35-B49: Micosis ──────────────────────────────────────────────────────
  { code: 'B35', desc: 'Dermatofitosis' },
  { code: 'B35.0', desc: 'Tiña de la barba y del cuero cabelludo' },
  { code: 'B35.1', desc: 'Tiña de las uñas' },
  { code: 'B35.2', desc: 'Tiña de la mano' },
  { code: 'B35.3', desc: 'Tiña del pie (pie de atleta)' },
  { code: 'B35.4', desc: 'Tiña del cuerpo' },
  { code: 'B35.6', desc: 'Tinea inguinal' },
  { code: 'B36', desc: 'Otras micosis superficiales' },
  { code: 'B36.0', desc: 'Pitiriasis versicolor' },
  { code: 'B37', desc: 'Candidiasis' },
  { code: 'B37.0', desc: 'Estomatitis candidiásica (muget)' },
  { code: 'B37.3', desc: 'Candidiasis de la vulva y de la vagina' },
  { code: 'B37.4', desc: 'Candidiasis del pene y del prepucio' },
  { code: 'B44', desc: 'Aspergilosis' },
  // ── B50-B64: Enfermedades parasitarias ────────────────────────────────────
  { code: 'B50', desc: 'Paludismo (malaria) debido a Plasmodium falciparum' },
  { code: 'B51', desc: 'Paludismo (malaria) debido a Plasmodium vivax' },
  { code: 'B54', desc: 'Paludismo (malaria) no especificado' },
  { code: 'B58', desc: 'Toxoplasmosis' },
  { code: 'B65', desc: 'Esquistosomiasis' },
  { code: 'B68', desc: 'Teniasis' },
  { code: 'B76', desc: 'Anquilostomiasis' },
  { code: 'B77', desc: 'Ascariasis' },
  { code: 'B80', desc: 'Oxiuriasis' },
  { code: 'B82', desc: 'Parasitosis intestinal, sin otra especificación' },
  { code: 'B85', desc: 'Pediculosis' },
  { code: 'B86', desc: 'Escabiosis (sarna)' },
  // ── C: Neoplasias malignas ────────────────────────────────────────────────
  { code: 'C00', desc: 'Tumor maligno del labio' },
  { code: 'C02', desc: 'Tumor maligno de la lengua' },
  { code: 'C04', desc: 'Tumor maligno del piso de la boca' },
  { code: 'C07', desc: 'Tumor maligno de la glándula parótida' },
  { code: 'C10', desc: 'Tumor maligno de la orofaringe' },
  { code: 'C11', desc: 'Tumor maligno de la nasofaringe' },
  { code: 'C15', desc: 'Tumor maligno del esófago' },
  { code: 'C16', desc: 'Tumor maligno del estómago' },
  { code: 'C18', desc: 'Tumor maligno del colon' },
  { code: 'C19', desc: 'Tumor maligno de la unión rectosigmoidea' },
  { code: 'C20', desc: 'Tumor maligno del recto' },
  { code: 'C22', desc: 'Tumor maligno del hígado y de los conductos biliares intrahepáticos' },
  { code: 'C23', desc: 'Tumor maligno de la vesícula biliar' },
  { code: 'C25', desc: 'Tumor maligno del páncreas' },
  { code: 'C32', desc: 'Tumor maligno de la laringe' },
  { code: 'C34', desc: 'Tumor maligno de los bronquios y del pulmón' },
  { code: 'C43', desc: 'Melanoma maligno de la piel' },
  { code: 'C44', desc: 'Otros tumores malignos de la piel' },
  { code: 'C50', desc: 'Tumor maligno de la mama' },
  { code: 'C50.9', desc: 'Tumor maligno de la mama, parte no especificada' },
  { code: 'C53', desc: 'Tumor maligno del cuello del útero' },
  { code: 'C54', desc: 'Tumor maligno del cuerpo del útero' },
  { code: 'C55', desc: 'Tumor maligno del útero, parte no especificada' },
  { code: 'C56', desc: 'Tumor maligno del ovario' },
  { code: 'C61', desc: 'Tumor maligno de la próstata' },
  { code: 'C62', desc: 'Tumor maligno del testículo' },
  { code: 'C64', desc: 'Tumor maligno del riñón, excepto de la pelvis renal' },
  { code: 'C67', desc: 'Tumor maligno de la vejiga urinaria' },
  { code: 'C71', desc: 'Tumor maligno del encéfalo' },
  { code: 'C73', desc: 'Tumor maligno de la glándula tiroides' },
  { code: 'C80', desc: 'Tumor maligno sin especificación de localización' },
  { code: 'C81', desc: 'Enfermedad de Hodgkin' },
  { code: 'C82', desc: 'Linfoma no Hodgkin folicular' },
  { code: 'C83', desc: 'Linfoma no Hodgkin difuso' },
  { code: 'C90', desc: 'Mieloma múltiple y tumores malignos de células plasmáticas' },
  { code: 'C91', desc: 'Leucemia linfoide' },
  { code: 'C92', desc: 'Leucemia mieloide' },
  // ── D: Trastornos de la sangre ─────────────────────────────────────────────
  { code: 'D50', desc: 'Anemia por deficiencia de hierro' },
  { code: 'D50.0', desc: 'Anemia por deficiencia de hierro secundaria a pérdida de sangre' },
  { code: 'D50.9', desc: 'Anemia por deficiencia de hierro, no especificada' },
  { code: 'D51', desc: 'Anemia por deficiencia de vitamina B12' },
  { code: 'D52', desc: 'Anemia por deficiencia de folatos' },
  { code: 'D53', desc: 'Otras anemias nutricionales' },
  { code: 'D55', desc: 'Anemia debida a trastornos enzimáticos' },
  { code: 'D56', desc: 'Talasemia' },
  { code: 'D57', desc: 'Trastornos drepanocíticos' },
  { code: 'D59', desc: 'Anemia hemolítica adquirida' },
  { code: 'D60', desc: 'Anemia aplástica adquirida' },
  { code: 'D64', desc: 'Otras anemias' },
  { code: 'D64.9', desc: 'Anemia, no especificada' },
  { code: 'D65', desc: 'Coagulación intravascular diseminada' },
  { code: 'D66', desc: 'Deficiencia hereditaria del factor VIII (hemofilia A)' },
  { code: 'D69', desc: 'Púrpura y otras afecciones hemorrágicas' },
  { code: 'D69.3', desc: 'Púrpura trombocitopénica idiopática' },
  { code: 'D70', desc: 'Agranulocitosis' },
  { code: 'D72', desc: 'Otros trastornos de los leucocitos' },
  { code: 'D73', desc: 'Enfermedades del bazo' },
  // ── E: Enfermedades endocrinas, nutricionales y metabólicas ───────────────
  { code: 'E00', desc: 'Síndrome de deficiencia de yodo congénito' },
  { code: 'E01', desc: 'Trastornos tiroideos relacionados con deficiencia de yodo' },
  { code: 'E02', desc: 'Hipotiroidismo subclínico por deficiencia de yodo' },
  { code: 'E03', desc: 'Otro hipotiroidismo' },
  { code: 'E03.0', desc: 'Hipotiroidismo congénito con bocio difuso' },
  { code: 'E03.1', desc: 'Hipotiroidismo congénito sin bocio' },
  { code: 'E03.9', desc: 'Hipotiroidismo, no especificado' },
  { code: 'E04', desc: 'Otro bocio no tóxico' },
  { code: 'E04.0', desc: 'Bocio no tóxico difuso' },
  { code: 'E04.1', desc: 'Bocio no tóxico uninodular' },
  { code: 'E04.2', desc: 'Bocio no tóxico multinodular' },
  { code: 'E05', desc: 'Tirotoxicosis (hipertiroidismo)' },
  { code: 'E05.0', desc: 'Tirotoxicosis con bocio difuso (Graves)' },
  { code: 'E05.9', desc: 'Tirotoxicosis, no especificada' },
  { code: 'E06', desc: 'Tiroiditis' },
  { code: 'E06.3', desc: 'Tiroiditis autoinmune (Hashimoto)' },
  { code: 'E07', desc: 'Otros trastornos de la glándula tiroides' },
  { code: 'E10', desc: 'Diabetes mellitus tipo 1' },
  { code: 'E10.0', desc: 'Diabetes mellitus tipo 1 con coma' },
  { code: 'E10.2', desc: 'Diabetes mellitus tipo 1 con complicaciones renales' },
  { code: 'E10.3', desc: 'Diabetes mellitus tipo 1 con complicaciones oftálmicas' },
  { code: 'E10.4', desc: 'Diabetes mellitus tipo 1 con complicaciones neurológicas' },
  { code: 'E10.5', desc: 'Diabetes mellitus tipo 1 con complicaciones circulatorias periféricas' },
  { code: 'E10.9', desc: 'Diabetes mellitus tipo 1 sin complicaciones' },
  { code: 'E11', desc: 'Diabetes mellitus tipo 2' },
  { code: 'E11.0', desc: 'Diabetes mellitus tipo 2 con coma' },
  { code: 'E11.2', desc: 'Diabetes mellitus tipo 2 con complicaciones renales' },
  { code: 'E11.3', desc: 'Diabetes mellitus tipo 2 con complicaciones oftálmicas' },
  { code: 'E11.4', desc: 'Diabetes mellitus tipo 2 con complicaciones neurológicas' },
  { code: 'E11.5', desc: 'Diabetes mellitus tipo 2 con complicaciones circulatorias periféricas' },
  { code: 'E11.6', desc: 'Diabetes mellitus tipo 2 con otras complicaciones especificadas' },
  { code: 'E11.65', desc: 'Diabetes mellitus tipo 2 con hiperglucemia' },
  { code: 'E11.9', desc: 'Diabetes mellitus tipo 2 sin complicaciones' },
  { code: 'E12', desc: 'Diabetes mellitus asociada con desnutrición' },
  { code: 'E13', desc: 'Otras diabetes mellitus especificadas' },
  { code: 'E14', desc: 'Diabetes mellitus, no especificada' },
  { code: 'E20', desc: 'Hipoparatiroidismo' },
  { code: 'E21', desc: 'Hiperparatiroidismo y otros trastornos de la glándula paratiroidea' },
  { code: 'E22', desc: 'Hiperfunción de la hipófisis' },
  { code: 'E23', desc: 'Hipofunción y otros trastornos de la hipófisis' },
  { code: 'E24', desc: 'Síndrome de Cushing' },
  { code: 'E25', desc: 'Trastornos adrenogenitales' },
  { code: 'E26', desc: 'Hiperaldosteronismo' },
  { code: 'E27', desc: 'Otros trastornos de la glándula suprarrenal' },
  { code: 'E27.1', desc: 'Insuficiencia corticosuprarrenal primaria (Addison)' },
  { code: 'E28', desc: 'Disfunción ovárica' },
  { code: 'E28.2', desc: 'Síndrome de ovario poliquístico' },
  { code: 'E29', desc: 'Disfunción testicular' },
  { code: 'E34', desc: 'Otros trastornos endocrinos' },
  { code: 'E40', desc: 'Kwashiorkor' },
  { code: 'E41', desc: 'Marasmo nutricional' },
  { code: 'E43', desc: 'Desnutrición proteico-calórica grave, no especificada' },
  { code: 'E44', desc: 'Desnutrición proteico-calórica de grado moderado y leve' },
  { code: 'E45', desc: 'Retardo del desarrollo debido a desnutrición proteico-calórica' },
  { code: 'E46', desc: 'Desnutrición proteico-calórica, no especificada' },
  { code: 'E50', desc: 'Deficiencia de vitamina A' },
  { code: 'E55', desc: 'Deficiencia de vitamina D' },
  { code: 'E55.9', desc: 'Deficiencia de vitamina D, no especificada' },
  { code: 'E56', desc: 'Otras deficiencias vitamínicas' },
  { code: 'E58', desc: 'Deficiencia alimentaria de calcio' },
  { code: 'E60', desc: 'Deficiencia alimentaria de zinc' },
  { code: 'E61', desc: 'Deficiencia de otros elementos nutricionales' },
  { code: 'E63', desc: 'Otras deficiencias nutricionales' },
  { code: 'E65', desc: 'Adiposidad localizada' },
  { code: 'E66', desc: 'Obesidad' },
  { code: 'E66.0', desc: 'Obesidad debida a exceso de calorías' },
  { code: 'E66.1', desc: 'Obesidad inducida por drogas' },
  { code: 'E66.9', desc: 'Obesidad, no especificada' },
  { code: 'E67', desc: 'Otros hiperalimentaciones' },
  { code: 'E70', desc: 'Trastornos del metabolismo de los aminoácidos aromáticos' },
  { code: 'E71', desc: 'Trastornos del metabolismo de los aminoácidos de cadena ramificada' },
  { code: 'E72', desc: 'Otros trastornos del metabolismo de los aminoácidos' },
  { code: 'E73', desc: 'Intolerancia a la lactosa' },
  { code: 'E74', desc: 'Otros trastornos del metabolismo de los carbohidratos' },
  { code: 'E75', desc: 'Trastornos del metabolismo de los esfingolípidos' },
  { code: 'E76', desc: 'Trastornos del metabolismo de los glucosaminoglucanos' },
  { code: 'E78', desc: 'Trastornos del metabolismo de las lipoproteínas' },
  { code: 'E78.0', desc: 'Hipercolesterolemia pura' },
  { code: 'E78.1', desc: 'Hipergliceridemia pura' },
  { code: 'E78.2', desc: 'Hiperlipidemia mixta' },
  { code: 'E78.4', desc: 'Otras hiperlipidemias' },
  { code: 'E78.5', desc: 'Hiperlipidemia, no especificada' },
  { code: 'E79', desc: 'Trastornos del metabolismo de las purinas y pirimidinas' },
  { code: 'E79.0', desc: 'Hiperuricemia sin signos de artritis gotosa' },
  { code: 'E80', desc: 'Trastornos del metabolismo de las porfirinas' },
  { code: 'E83', desc: 'Trastornos del metabolismo de los minerales' },
  { code: 'E83.0', desc: 'Trastornos del metabolismo del cobre' },
  { code: 'E83.1', desc: 'Trastornos del metabolismo del hierro' },
  { code: 'E83.5', desc: 'Trastornos del metabolismo del calcio' },
  { code: 'E84', desc: 'Fibrosis quística' },
  { code: 'E85', desc: 'Amiloidosis' },
  { code: 'E86', desc: 'Depleción del volumen' },
  { code: 'E87', desc: 'Otros trastornos del equilibrio de los líquidos, electrólitos y ácido-base' },
  { code: 'E87.0', desc: 'Hiperosmolaridad e hipernatremia' },
  { code: 'E87.1', desc: 'Hiposmolaridad e hiponatremia' },
  { code: 'E87.2', desc: 'Acidosis' },
  { code: 'E87.3', desc: 'Alcalosis' },
  { code: 'E87.5', desc: 'Hiperpotasemia (hipercaliemia)' },
  { code: 'E87.6', desc: 'Hipopotasemia (hipocaliemia)' },
  { code: 'E88', desc: 'Otros trastornos metabólicos' },
  { code: 'E89', desc: 'Trastornos metabólicos y endocrinos consecutivos a procedimientos' },
  // ── F: Trastornos mentales ────────────────────────────────────────────────
  { code: 'F00', desc: 'Demencia en la enfermedad de Alzheimer' },
  { code: 'F01', desc: 'Demencia vascular' },
  { code: 'F03', desc: 'Demencia, no especificada' },
  { code: 'F04', desc: 'Síndrome amnésico orgánico' },
  { code: 'F05', desc: 'Delirium, no inducido por alcohol u otras sustancias psicoactivas' },
  { code: 'F06', desc: 'Otros trastornos mentales debidos a lesión cerebral' },
  { code: 'F10', desc: 'Trastornos mentales y del comportamiento debidos al uso de alcohol' },
  { code: 'F10.0', desc: 'Intoxicación aguda por alcohol' },
  { code: 'F10.1', desc: 'Uso nocivo de alcohol' },
  { code: 'F10.2', desc: 'Síndrome de dependencia del alcohol' },
  { code: 'F11', desc: 'Trastornos mentales y del comportamiento debidos al uso de opioides' },
  { code: 'F12', desc: 'Trastornos mentales y del comportamiento debidos al uso de cannabinoides' },
  { code: 'F14', desc: 'Trastornos mentales y del comportamiento debidos al uso de cocaína' },
  { code: 'F17', desc: 'Trastornos mentales y del comportamiento debidos al uso de tabaco' },
  { code: 'F17.1', desc: 'Uso nocivo de tabaco' },
  { code: 'F20', desc: 'Esquizofrenia' },
  { code: 'F20.0', desc: 'Esquizofrenia paranoide' },
  { code: 'F20.9', desc: 'Esquizofrenia, no especificada' },
  { code: 'F25', desc: 'Trastorno esquizoafectivo' },
  { code: 'F29', desc: 'Psicosis no orgánica, no especificada' },
  { code: 'F30', desc: 'Episodio maníaco' },
  { code: 'F31', desc: 'Trastorno afectivo bipolar' },
  { code: 'F32', desc: 'Episodios depresivos' },
  { code: 'F32.0', desc: 'Episodio depresivo leve' },
  { code: 'F32.1', desc: 'Episodio depresivo moderado' },
  { code: 'F32.2', desc: 'Episodio depresivo grave sin síntomas psicóticos' },
  { code: 'F32.9', desc: 'Episodio depresivo, no especificado' },
  { code: 'F33', desc: 'Trastorno depresivo recurrente' },
  { code: 'F33.9', desc: 'Trastorno depresivo recurrente, no especificado' },
  { code: 'F40', desc: 'Trastornos fóbicos de ansiedad' },
  { code: 'F40.0', desc: 'Agorafobia' },
  { code: 'F40.1', desc: 'Fobias sociales' },
  { code: 'F41', desc: 'Otros trastornos de ansiedad' },
  { code: 'F41.0', desc: 'Trastorno de pánico' },
  { code: 'F41.1', desc: 'Trastorno de ansiedad generalizada' },
  { code: 'F41.9', desc: 'Trastorno de ansiedad, no especificado' },
  { code: 'F42', desc: 'Trastorno obsesivo-compulsivo' },
  { code: 'F43', desc: 'Reacciones al estrés grave y trastornos de adaptación' },
  { code: 'F43.0', desc: 'Reacción al estrés agudo' },
  { code: 'F43.1', desc: 'Trastorno de estrés postraumático' },
  { code: 'F43.2', desc: 'Trastorno de adaptación' },
  { code: 'F44', desc: 'Trastornos disociativos (de conversión)' },
  { code: 'F45', desc: 'Trastornos somatomorfos' },
  { code: 'F50', desc: 'Trastornos de la conducta alimentaria' },
  { code: 'F50.0', desc: 'Anorexia nerviosa' },
  { code: 'F50.2', desc: 'Bulimia nerviosa' },
  { code: 'F51', desc: 'Trastornos del sueño no orgánicos' },
  { code: 'F60', desc: 'Trastornos específicos de la personalidad' },
  { code: 'F70', desc: 'Retraso mental leve' },
  { code: 'F79', desc: 'Retraso mental, no especificado' },
  { code: 'F80', desc: 'Trastornos específicos del desarrollo del habla y del lenguaje' },
  { code: 'F84', desc: 'Trastornos generalizados del desarrollo' },
  { code: 'F84.0', desc: 'Autismo en la niñez' },
  { code: 'F90', desc: 'Trastornos hipercinéticos (TDAH)' },
  { code: 'F90.0', desc: 'Perturbación de la actividad y de la atención' },
  { code: 'F91', desc: 'Trastornos de la conducta' },
  { code: 'F99', desc: 'Trastorno mental, no especificado' },
  // ── G: Enfermedades del sistema nervioso ──────────────────────────────────
  { code: 'G00', desc: 'Meningitis bacteriana' },
  { code: 'G03', desc: 'Meningitis debida a otras causas y causas no especificadas' },
  { code: 'G04', desc: 'Encefalitis, mielitis y encefalomielitis' },
  { code: 'G20', desc: 'Enfermedad de Parkinson' },
  { code: 'G30', desc: 'Enfermedad de Alzheimer' },
  { code: 'G35', desc: 'Esclerosis múltiple' },
  { code: 'G40', desc: 'Epilepsia' },
  { code: 'G40.0', desc: 'Epilepsia y síndromes epilépticos idiopáticos focales (parciales)' },
  { code: 'G40.3', desc: 'Epilepsia y síndromes epilépticos idiopáticos generalizados' },
  { code: 'G40.9', desc: 'Epilepsia, tipo no especificado' },
  { code: 'G41', desc: 'Estado epiléptico' },
  { code: 'G43', desc: 'Migraña' },
  { code: 'G43.0', desc: 'Migraña sin aura (migraña común)' },
  { code: 'G43.1', desc: 'Migraña con aura (migraña clásica)' },
  { code: 'G43.9', desc: 'Migraña, no especificada' },
  { code: 'G44', desc: 'Otros síndromes de cefalea' },
  { code: 'G45', desc: 'Ataques de isquemia cerebral transitoria y síndromes afines' },
  { code: 'G47', desc: 'Trastornos del sueño' },
  { code: 'G47.0', desc: 'Trastornos para conciliar el sueño y permanecer dormido (insomnio)' },
  { code: 'G47.3', desc: 'Apnea del sueño' },
  { code: 'G50', desc: 'Trastornos del nervio trigémino' },
  { code: 'G50.0', desc: 'Neuralgia del trigémino' },
  { code: 'G51', desc: 'Trastornos del nervio facial' },
  { code: 'G51.0', desc: 'Parálisis de Bell' },
  { code: 'G54', desc: 'Trastornos de las raíces y plexos nerviosos' },
  { code: 'G54.2', desc: 'Radiculopatía cervical' },
  { code: 'G54.4', desc: 'Radiculopatía lumbar' },
  { code: 'G56', desc: 'Mononeuropatías del miembro superior' },
  { code: 'G56.0', desc: 'Síndrome del túnel carpiano' },
  { code: 'G57', desc: 'Mononeuropatías del miembro inferior' },
  { code: 'G57.0', desc: 'Lesión del nervio ciático' },
  { code: 'G57.1', desc: 'Meralgia parestética' },
  { code: 'G60', desc: 'Neuropatía hereditaria e idiopática' },
  { code: 'G61', desc: 'Polineuropatía inflamatoria' },
  { code: 'G61.0', desc: 'Síndrome de Guillain-Barré' },
  { code: 'G62', desc: 'Otras polineuropatías' },
  { code: 'G62.9', desc: 'Polineuropatía, no especificada' },
  { code: 'G63', desc: 'Polineuropatía en enfermedades clasificadas en otra parte (diabética)' },
  { code: 'G70', desc: 'Miastenia gravis y otros trastornos neuromusculares' },
  { code: 'G80', desc: 'Parálisis cerebral' },
  { code: 'G81', desc: 'Hemiplejía' },
  { code: 'G82', desc: 'Paraplejía y tetraplejía' },
  { code: 'G89', desc: 'Dolor no clasificado en otra parte' },
  { code: 'G91', desc: 'Hidrocefalia' },
  { code: 'G93', desc: 'Otros trastornos del encéfalo' },
  // ── H: Enfermedades del ojo y del oído ────────────────────────────────────
  { code: 'H00', desc: 'Orzuelo y chalazión' },
  { code: 'H01', desc: 'Otras inflamaciones del párpado' },
  { code: 'H04', desc: 'Trastornos del aparato lagrimal' },
  { code: 'H10', desc: 'Conjuntivitis' },
  { code: 'H10.1', desc: 'Conjuntivitis aguda atópica' },
  { code: 'H10.3', desc: 'Conjuntivitis aguda no especificada' },
  { code: 'H11', desc: 'Otros trastornos de la conjuntiva' },
  { code: 'H16', desc: 'Queratitis' },
  { code: 'H25', desc: 'Catarata senil' },
  { code: 'H26', desc: 'Otras cataratas' },
  { code: 'H33', desc: 'Desprendimiento y desgarro de la retina' },
  { code: 'H35', desc: 'Otros trastornos de la retina' },
  { code: 'H36', desc: 'Trastornos de la retina en enfermedades clasificadas en otra parte' },
  { code: 'H40', desc: 'Glaucoma' },
  { code: 'H40.1', desc: 'Glaucoma primario de ángulo abierto' },
  { code: 'H40.9', desc: 'Glaucoma, no especificado' },
  { code: 'H52', desc: 'Trastornos de la acomodación y de la refracción' },
  { code: 'H52.0', desc: 'Hipermetropía' },
  { code: 'H52.1', desc: 'Miopía' },
  { code: 'H52.2', desc: 'Astigmatismo' },
  { code: 'H52.4', desc: 'Presbicia' },
  { code: 'H60', desc: 'Otitis externa' },
  { code: 'H61', desc: 'Otros trastornos del oído externo' },
  { code: 'H65', desc: 'Otitis media no supurativa' },
  { code: 'H65.0', desc: 'Otitis media aguda serosa' },
  { code: 'H65.9', desc: 'Otitis media no supurativa, no especificada' },
  { code: 'H66', desc: 'Otitis media supurativa' },
  { code: 'H66.0', desc: 'Otitis media supurativa aguda' },
  { code: 'H66.9', desc: 'Otitis media, no especificada' },
  { code: 'H72', desc: 'Perforación de la membrana timpánica' },
  { code: 'H81', desc: 'Trastornos de la función vestibular' },
  { code: 'H81.0', desc: 'Enfermedad de Ménière' },
  { code: 'H81.3', desc: 'Otros vértigos periféricos' },
  { code: 'H83', desc: 'Otros trastornos del oído interno' },
  { code: 'H90', desc: 'Hipoacusia conductiva y neurosensorial' },
  { code: 'H91', desc: 'Otros tipos de pérdida de la audición' },
  { code: 'H91.9', desc: 'Pérdida de la audición, no especificada' },
  // ── I: Enfermedades del sistema circulatorio ──────────────────────────────
  { code: 'I05', desc: 'Enfermedades reumáticas de la válvula mitral' },
  { code: 'I08', desc: 'Enfermedades de múltiples válvulas cardíacas' },
  { code: 'I10', desc: 'Hipertensión esencial (primaria)' },
  { code: 'I11', desc: 'Enfermedad cardíaca hipertensiva' },
  { code: 'I12', desc: 'Enfermedad renal hipertensiva' },
  { code: 'I13', desc: 'Enfermedad cardíaca e hipertensión renal' },
  { code: 'I15', desc: 'Hipertensión secundaria' },
  { code: 'I20', desc: 'Angina de pecho' },
  { code: 'I20.0', desc: 'Angina inestable' },
  { code: 'I20.9', desc: 'Angina de pecho, no especificada' },
  { code: 'I21', desc: 'Infarto agudo de miocardio' },
  { code: 'I21.9', desc: 'Infarto agudo de miocardio, no especificado' },
  { code: 'I22', desc: 'Infarto subsiguiente de miocardio' },
  { code: 'I25', desc: 'Enfermedad isquémica crónica del corazón' },
  { code: 'I25.1', desc: 'Enfermedad aterosclerótica del corazón' },
  { code: 'I26', desc: 'Embolia pulmonar' },
  { code: 'I27', desc: 'Otras enfermedades cardiopulmonares' },
  { code: 'I30', desc: 'Pericarditis aguda' },
  { code: 'I33', desc: 'Endocarditis aguda y subaguda' },
  { code: 'I34', desc: 'Trastornos no reumáticos de la válvula mitral' },
  { code: 'I35', desc: 'Trastornos no reumáticos de la válvula aórtica' },
  { code: 'I38', desc: 'Endocarditis, válvula no especificada' },
  { code: 'I42', desc: 'Cardiomiopatía' },
  { code: 'I44', desc: 'Bloqueo auriculoventricular y de rama izquierda del haz' },
  { code: 'I46', desc: 'Paro cardíaco' },
  { code: 'I47', desc: 'Taquicardia paroxística' },
  { code: 'I48', desc: 'Fibrilación y aleteo auricular' },
  { code: 'I49', desc: 'Otras arritmias cardíacas' },
  { code: 'I50', desc: 'Insuficiencia cardíaca' },
  { code: 'I50.0', desc: 'Insuficiencia cardíaca congestiva' },
  { code: 'I50.9', desc: 'Insuficiencia cardíaca, no especificada' },
  { code: 'I60', desc: 'Hemorragia subaracnoidea' },
  { code: 'I61', desc: 'Hemorragia intracerebral' },
  { code: 'I63', desc: 'Infarto cerebral' },
  { code: 'I63.9', desc: 'Infarto cerebral, no especificado' },
  { code: 'I64', desc: 'Accidente vascular encefálico agudo, no especificado como hemorrágico' },
  { code: 'I65', desc: 'Oclusión y estenosis de las arterias precerebrales' },
  { code: 'I66', desc: 'Oclusión y estenosis de las arterias cerebrales' },
  { code: 'I67', desc: 'Otras enfermedades cerebrovasculares' },
  { code: 'I69', desc: 'Secuelas de enfermedades cerebrovasculares' },
  { code: 'I70', desc: 'Aterosclerosis' },
  { code: 'I70.0', desc: 'Aterosclerosis de la aorta' },
  { code: 'I70.2', desc: 'Aterosclerosis de las arterias de las extremidades' },
  { code: 'I71', desc: 'Aneurisma y disección de la aorta' },
  { code: 'I73', desc: 'Otras enfermedades vasculares periféricas' },
  { code: 'I73.0', desc: 'Síndrome de Raynaud' },
  { code: 'I74', desc: 'Embolia y trombosis arteriales' },
  { code: 'I80', desc: 'Flebitis y tromboflebitis' },
  { code: 'I83', desc: 'Venas varicosas de las extremidades inferiores' },
  { code: 'I84', desc: 'Hemorroides' },
  { code: 'I86', desc: 'Várices de otros sitios' },
  { code: 'I87', desc: 'Otros trastornos venosos' },
  { code: 'I89', desc: 'Otros trastornos no infecciosos de los vasos linfáticos' },
  { code: 'I95', desc: 'Hipotensión' },
  { code: 'I95.1', desc: 'Hipotensión ortostática' },
  // ── J: Enfermedades respiratorias ─────────────────────────────────────────
  { code: 'J00', desc: 'Rinofaringitis aguda (resfriado común)' },
  { code: 'J01', desc: 'Sinusitis aguda' },
  { code: 'J01.0', desc: 'Sinusitis maxilar aguda' },
  { code: 'J01.9', desc: 'Sinusitis aguda, no especificada' },
  { code: 'J02', desc: 'Faringitis aguda' },
  { code: 'J02.0', desc: 'Faringitis estreptocócica' },
  { code: 'J02.9', desc: 'Faringitis aguda, no especificada' },
  { code: 'J03', desc: 'Amigdalitis aguda' },
  { code: 'J03.0', desc: 'Amigdalitis estreptocócica' },
  { code: 'J03.9', desc: 'Amigdalitis aguda, no especificada' },
  { code: 'J04', desc: 'Laringitis y traqueítis agudas' },
  { code: 'J05', desc: 'Laringitis obstructiva aguda (croup) y epiglotitis' },
  { code: 'J06', desc: 'Infecciones agudas de las vías respiratorias superiores' },
  { code: 'J06.9', desc: 'Infección aguda de las vías respiratorias superiores, no especificada' },
  { code: 'J09', desc: 'Influenza debida a ciertos virus gripales identificados' },
  { code: 'J10', desc: 'Influenza debida a otro virus de la influenza identificado' },
  { code: 'J11', desc: 'Influenza debida a virus no identificado' },
  { code: 'J11.0', desc: 'Influenza con neumonía, virus no identificado' },
  { code: 'J11.1', desc: 'Influenza con otras manifestaciones respiratorias, virus no identificado' },
  { code: 'J12', desc: 'Neumonía viral' },
  { code: 'J13', desc: 'Neumonía debida a Streptococcus pneumoniae' },
  { code: 'J14', desc: 'Neumonía debida a Haemophilus influenzae' },
  { code: 'J15', desc: 'Neumonía bacteriana' },
  { code: 'J15.9', desc: 'Neumonía bacteriana, no especificada' },
  { code: 'J18', desc: 'Neumonía, organismo no especificado' },
  { code: 'J18.9', desc: 'Neumonía, no especificada' },
  { code: 'J20', desc: 'Bronquitis aguda' },
  { code: 'J20.9', desc: 'Bronquitis aguda, no especificada' },
  { code: 'J22', desc: 'Infección aguda de las vías respiratorias inferiores, no especificada' },
  { code: 'J30', desc: 'Rinitis alérgica y vasomotora' },
  { code: 'J30.1', desc: 'Rinitis alérgica debida a polen' },
  { code: 'J30.4', desc: 'Rinitis alérgica, no especificada' },
  { code: 'J31', desc: 'Rinitis crónica, nasofaringitis y faringoamigdalitis' },
  { code: 'J32', desc: 'Sinusitis crónica' },
  { code: 'J35', desc: 'Enfermedades crónicas de las amígdalas y adenoides' },
  { code: 'J35.0', desc: 'Amigdalitis crónica' },
  { code: 'J36', desc: 'Absceso periamigdalino' },
  { code: 'J37', desc: 'Laringitis crónica y laringotraqueítis' },
  { code: 'J38', desc: 'Enfermedades de las cuerdas vocales y de la laringe' },
  { code: 'J40', desc: 'Bronquitis, no especificada como aguda o crónica' },
  { code: 'J41', desc: 'Bronquitis crónica simple y mucopurulenta' },
  { code: 'J42', desc: 'Bronquitis crónica, no especificada' },
  { code: 'J43', desc: 'Enfisema' },
  { code: 'J44', desc: 'Enfermedad pulmonar obstructiva crónica (EPOC)' },
  { code: 'J44.0', desc: 'EPOC con infección respiratoria aguda de las vías respiratorias inferiores' },
  { code: 'J44.1', desc: 'EPOC con exacerbación aguda, no especificada' },
  { code: 'J44.9', desc: 'EPOC, no especificada' },
  { code: 'J45', desc: 'Asma' },
  { code: 'J45.0', desc: 'Asma predominantemente alérgica' },
  { code: 'J45.1', desc: 'Asma no alérgica' },
  { code: 'J45.9', desc: 'Asma, no especificada' },
  { code: 'J46', desc: 'Estado asmático' },
  { code: 'J47', desc: 'Bronquiectasia' },
  { code: 'J80', desc: 'Síndrome de dificultad respiratoria del adulto' },
  { code: 'J81', desc: 'Edema pulmonar' },
  { code: 'J84', desc: 'Otras enfermedades pulmonares intersticiales' },
  { code: 'J90', desc: 'Derrame pleural' },
  { code: 'J93', desc: 'Neumotórax' },
  { code: 'J96', desc: 'Insuficiencia respiratoria' },
  { code: 'J96.0', desc: 'Insuficiencia respiratoria aguda' },
  { code: 'J96.1', desc: 'Insuficiencia respiratoria crónica' },
  { code: 'J98', desc: 'Otros trastornos respiratorios' },
  // ── K: Enfermedades del aparato digestivo ─────────────────────────────────
  { code: 'K00', desc: 'Trastornos del desarrollo y de la erupción de los dientes' },
  { code: 'K02', desc: 'Caries dental' },
  { code: 'K04', desc: 'Enfermedades de la pulpa y de los tejidos periapicales' },
  { code: 'K05', desc: 'Gingivitis y enfermedades periodontales' },
  { code: 'K08', desc: 'Otros trastornos de los dientes y de sus estructuras de sostén' },
  { code: 'K11', desc: 'Enfermedades de las glándulas salivales' },
  { code: 'K13', desc: 'Otras enfermedades de los labios y de la mucosa oral' },
  { code: 'K20', desc: 'Esofagitis' },
  { code: 'K21', desc: 'Enfermedad de reflujo gastroesofágico (ERGE)' },
  { code: 'K21.0', desc: 'Enfermedad de reflujo gastroesofágico con esofagitis' },
  { code: 'K21.9', desc: 'Enfermedad de reflujo gastroesofágico sin esofagitis' },
  { code: 'K22', desc: 'Otras enfermedades del esófago' },
  { code: 'K25', desc: 'Úlcera gástrica' },
  { code: 'K25.9', desc: 'Úlcera gástrica, no especificada como aguda o crónica' },
  { code: 'K26', desc: 'Úlcera duodenal' },
  { code: 'K26.9', desc: 'Úlcera duodenal, no especificada como aguda o crónica' },
  { code: 'K27', desc: 'Úlcera péptica, no especificada' },
  { code: 'K29', desc: 'Gastritis y duodenitis' },
  { code: 'K29.0', desc: 'Gastritis aguda hemorrágica' },
  { code: 'K29.7', desc: 'Gastritis, no especificada' },
  { code: 'K30', desc: 'Dispepsia' },
  { code: 'K31', desc: 'Otras enfermedades del estómago y del duodeno' },
  { code: 'K35', desc: 'Apendicitis aguda' },
  { code: 'K35.8', desc: 'Apendicitis aguda, sin peritonitis' },
  { code: 'K36', desc: 'Otras apendicitis' },
  { code: 'K37', desc: 'Apendicitis, no especificada' },
  { code: 'K40', desc: 'Hernia inguinal' },
  { code: 'K40.9', desc: 'Hernia inguinal unilateral, sin obstrucción ni gangrena' },
  { code: 'K41', desc: 'Hernia femoral' },
  { code: 'K42', desc: 'Hernia umbilical' },
  { code: 'K43', desc: 'Hernia ventral' },
  { code: 'K44', desc: 'Hernia diafragmática' },
  { code: 'K46', desc: 'Hernia abdominal no especificada' },
  { code: 'K50', desc: 'Enfermedad de Crohn' },
  { code: 'K50.9', desc: 'Enfermedad de Crohn, no especificada' },
  { code: 'K51', desc: 'Colitis ulcerativa' },
  { code: 'K51.9', desc: 'Colitis ulcerativa, no especificada' },
  { code: 'K52', desc: 'Otras colitis y gastroenteritis no infecciosas' },
  { code: 'K55', desc: 'Trastornos vasculares del intestino' },
  { code: 'K57', desc: 'Enfermedad diverticular del intestino' },
  { code: 'K58', desc: 'Síndrome del colon irritable' },
  { code: 'K58.0', desc: 'Síndrome del colon irritable con diarrea' },
  { code: 'K58.9', desc: 'Síndrome del colon irritable sin diarrea' },
  { code: 'K59', desc: 'Otros trastornos funcionales del intestino' },
  { code: 'K59.0', desc: 'Estreñimiento' },
  { code: 'K60', desc: 'Fisura y fístula de las regiones anal y rectal' },
  { code: 'K61', desc: 'Absceso de las regiones anal y rectal' },
  { code: 'K63', desc: 'Otras enfermedades del intestino' },
  { code: 'K64', desc: 'Hemorroides y trombosis venosa perianal' },
  { code: 'K65', desc: 'Peritonitis' },
  { code: 'K70', desc: 'Enfermedad hepática alcohólica' },
  { code: 'K71', desc: 'Enfermedad hepática tóxica' },
  { code: 'K72', desc: 'Insuficiencia hepática' },
  { code: 'K73', desc: 'Hepatitis crónica, no clasificada en otra parte' },
  { code: 'K74', desc: 'Fibrosis y cirrosis del hígado' },
  { code: 'K74.6', desc: 'Otras cirrosis del hígado y las no especificadas' },
  { code: 'K76', desc: 'Otras enfermedades del hígado' },
  { code: 'K76.0', desc: 'Degeneración grasa del hígado (esteatohepatitis no alcohólica)' },
  { code: 'K80', desc: 'Colelitiasis (cálculos biliares)' },
  { code: 'K80.0', desc: 'Cálculos de la vesícula biliar con colecistitis aguda' },
  { code: 'K80.2', desc: 'Cálculos de la vesícula biliar sin colecistitis' },
  { code: 'K81', desc: 'Colecistitis' },
  { code: 'K81.0', desc: 'Colecistitis aguda' },
  { code: 'K81.1', desc: 'Colecistitis crónica' },
  { code: 'K85', desc: 'Pancreatitis aguda' },
  { code: 'K86', desc: 'Otras enfermedades del páncreas' },
  { code: 'K86.1', desc: 'Otras pancreatitis crónicas' },
  { code: 'K87', desc: 'Trastornos de la vesícula biliar, vías biliares y páncreas en enfermedades' },
  { code: 'K90', desc: 'Malabsorción intestinal' },
  { code: 'K90.0', desc: 'Enfermedad celiaca' },
  { code: 'K92', desc: 'Otras enfermedades del aparato digestivo' },
  { code: 'K92.0', desc: 'Hematemesis' },
  { code: 'K92.1', desc: 'Melena' },
  { code: 'K92.2', desc: 'Hemorragia gastrointestinal, no especificada' },
  // ── L: Enfermedades de la piel ────────────────────────────────────────────
  { code: 'L01', desc: 'Impétigo' },
  { code: 'L02', desc: 'Absceso cutáneo, furúnculo y carbunco' },
  { code: 'L03', desc: 'Celulitis' },
  { code: 'L04', desc: 'Linfadenitis aguda' },
  { code: 'L05', desc: 'Quiste pilonidal' },
  { code: 'L08', desc: 'Otras infecciones locales de la piel y del tejido subcutáneo' },
  { code: 'L20', desc: 'Dermatitis atópica' },
  { code: 'L21', desc: 'Dermatitis seborreica' },
  { code: 'L22', desc: 'Dermatitis del pañal' },
  { code: 'L23', desc: 'Dermatitis alérgica de contacto' },
  { code: 'L24', desc: 'Dermatitis irritativa de contacto' },
  { code: 'L25', desc: 'Dermatitis de contacto, no especificada' },
  { code: 'L27', desc: 'Dermatitis debida a sustancias tomadas internamente' },
  { code: 'L28', desc: 'Liquen simple crónico y prurigo' },
  { code: 'L29', desc: 'Prurito' },
  { code: 'L30', desc: 'Otras dermatitis' },
  { code: 'L30.9', desc: 'Dermatitis, no especificada' },
  { code: 'L40', desc: 'Psoriasis' },
  { code: 'L40.0', desc: 'Psoriasis vulgar' },
  { code: 'L43', desc: 'Liquen plano' },
  { code: 'L50', desc: 'Urticaria' },
  { code: 'L50.0', desc: 'Urticaria alérgica' },
  { code: 'L50.9', desc: 'Urticaria, no especificada' },
  { code: 'L51', desc: 'Eritema multiforme' },
  { code: 'L52', desc: 'Eritema nudoso' },
  { code: 'L55', desc: 'Quemaduras solares' },
  { code: 'L57', desc: 'Cambios en la piel debidos a exposición crónica a radiación no ionizante' },
  { code: 'L60', desc: 'Trastornos de las uñas' },
  { code: 'L63', desc: 'Alopecia areata' },
  { code: 'L64', desc: 'Alopecia androgénica' },
  { code: 'L65', desc: 'Otras pérdidas no cicatriciales del cabello' },
  { code: 'L70', desc: 'Acné' },
  { code: 'L70.0', desc: 'Acné vulgar' },
  { code: 'L71', desc: 'Rosácea' },
  { code: 'L72', desc: 'Quistes foliculares de la piel y del tejido subcutáneo' },
  { code: 'L73', desc: 'Otros trastornos foliculares' },
  { code: 'L80', desc: 'Vitíligo' },
  { code: 'L81', desc: 'Otros trastornos de la pigmentación' },
  { code: 'L82', desc: 'Queratosis seborreica' },
  { code: 'L89', desc: 'Úlcera de decúbito' },
  { code: 'L92', desc: 'Trastornos granulomatosos de la piel y del tejido subcutáneo' },
  { code: 'L98', desc: 'Otros trastornos de la piel y del tejido subcutáneo' },
  // ── M: Enfermedades del sistema musculoesquelético ────────────────────────
  { code: 'M00', desc: 'Artritis piógena' },
  { code: 'M02', desc: 'Artropatías reactivas' },
  { code: 'M05', desc: 'Artritis reumatoide seropositiva' },
  { code: 'M05.3', desc: 'Artritis reumatoide con compromiso de otros órganos' },
  { code: 'M06', desc: 'Otras artritis reumatoides' },
  { code: 'M06.9', desc: 'Artritis reumatoide, no especificada' },
  { code: 'M08', desc: 'Artritis juvenil' },
  { code: 'M10', desc: 'Gota' },
  { code: 'M10.0', desc: 'Gota idiopática' },
  { code: 'M10.9', desc: 'Gota, no especificada' },
  { code: 'M13', desc: 'Otras artritis' },
  { code: 'M13.9', desc: 'Artritis, no especificada' },
  { code: 'M15', desc: 'Poliartrosis' },
  { code: 'M16', desc: 'Coxartrosis (artrosis de la cadera)' },
  { code: 'M16.9', desc: 'Coxartrosis, no especificada' },
  { code: 'M17', desc: 'Gonartrosis (artrosis de la rodilla)' },
  { code: 'M17.9', desc: 'Gonartrosis, no especificada' },
  { code: 'M19', desc: 'Otras artrosis' },
  { code: 'M19.9', desc: 'Artrosis, no especificada' },
  { code: 'M20', desc: 'Deformidades adquiridas de los dedos de la mano y del pie' },
  { code: 'M23', desc: 'Trastornos internos de la rodilla' },
  { code: 'M25', desc: 'Otros trastornos de las articulaciones' },
  { code: 'M25.5', desc: 'Dolor articular' },
  { code: 'M30', desc: 'Poliarteritis nudosa y afecciones similares' },
  { code: 'M32', desc: 'Lupus eritematoso sistémico' },
  { code: 'M33', desc: 'Dermatomiositis-polimiositis' },
  { code: 'M34', desc: 'Esclerosis sistémica' },
  { code: 'M35', desc: 'Otras enfermedades sistémicas del tejido conjuntivo' },
  { code: 'M35.0', desc: 'Síndrome seco (Sjögren)' },
  { code: 'M40', desc: 'Cifosis y lordosis' },
  { code: 'M41', desc: 'Escoliosis' },
  { code: 'M42', desc: 'Osteocondritis de la columna vertebral' },
  { code: 'M43', desc: 'Otras dorsopatías deformantes' },
  { code: 'M47', desc: 'Espondiloartrosis' },
  { code: 'M48', desc: 'Otras espondilopatías' },
  { code: 'M50', desc: 'Trastornos de disco cervical' },
  { code: 'M50.1', desc: 'Trastorno de disco cervical con radiculopatía' },
  { code: 'M51', desc: 'Trastornos de discos intervertebrales de otras regiones' },
  { code: 'M51.1', desc: 'Trastornos de disco lumbar y otros con radiculopatía' },
  { code: 'M54', desc: 'Dorsalgia' },
  { code: 'M54.2', desc: 'Cervicalgia' },
  { code: 'M54.3', desc: 'Ciática' },
  { code: 'M54.4', desc: 'Lumbago con ciática' },
  { code: 'M54.5', desc: 'Lumbago, no especificado' },
  { code: 'M54.9', desc: 'Dorsalgia, no especificada' },
  { code: 'M60', desc: 'Miositis' },
  { code: 'M61', desc: 'Calcificación y osificación del músculo' },
  { code: 'M62', desc: 'Otros trastornos musculares' },
  { code: 'M65', desc: 'Sinovitis y tenosinovitis' },
  { code: 'M70', desc: 'Trastornos de los tejidos blandos relacionados con uso, sobreesfuerzo' },
  { code: 'M71', desc: 'Otras bursopatías' },
  { code: 'M72', desc: 'Trastornos de la fascia' },
  { code: 'M75', desc: 'Lesiones del hombro' },
  { code: 'M75.0', desc: 'Capsulitis adhesiva del hombro (hombro congelado)' },
  { code: 'M75.1', desc: 'Síndrome del manguito de los rotadores' },
  { code: 'M76', desc: 'Entesopatatías del miembro inferior' },
  { code: 'M77', desc: 'Otras entesopatías' },
  { code: 'M77.0', desc: 'Epicondilitis medial' },
  { code: 'M77.1', desc: 'Epicondilitis lateral (codo de tenista)' },
  { code: 'M79', desc: 'Otros trastornos de los tejidos blandos' },
  { code: 'M79.0', desc: 'Reumatismo, no especificado' },
  { code: 'M79.1', desc: 'Mialgia' },
  { code: 'M79.2', desc: 'Neuralgia y neuritis, no especificadas' },
  { code: 'M79.3', desc: 'Paniculitis, no especificada' },
  { code: 'M79.7', desc: 'Fibromialgia' },
  { code: 'M80', desc: 'Osteoporosis con fractura patológica' },
  { code: 'M81', desc: 'Osteoporosis sin fractura patológica' },
  { code: 'M81.0', desc: 'Osteoporosis posmenopáusica' },
  { code: 'M81.9', desc: 'Osteoporosis, no especificada' },
  { code: 'M85', desc: 'Otros trastornos de la densidad y estructura óseas' },
  { code: 'M86', desc: 'Osteomielitis' },
  { code: 'M87', desc: 'Osteonecrosis' },
  // ── N: Enfermedades genitourinarias ───────────────────────────────────────
  { code: 'N00', desc: 'Síndrome nefrítico agudo' },
  { code: 'N02', desc: 'Hematuria recidivante y persistente' },
  { code: 'N03', desc: 'Síndrome nefrítico crónico' },
  { code: 'N04', desc: 'Síndrome nefrótico' },
  { code: 'N05', desc: 'Síndrome nefrítico, no especificado' },
  { code: 'N10', desc: 'Nefritis tubulointersticial aguda (pielonefritis aguda)' },
  { code: 'N11', desc: 'Nefritis tubulointersticial crónica (pielonefritis crónica)' },
  { code: 'N17', desc: 'Insuficiencia renal aguda' },
  { code: 'N17.9', desc: 'Insuficiencia renal aguda, no especificada' },
  { code: 'N18', desc: 'Insuficiencia renal crónica' },
  { code: 'N18.9', desc: 'Insuficiencia renal crónica, no especificada' },
  { code: 'N19', desc: 'Insuficiencia renal no especificada' },
  { code: 'N20', desc: 'Cálculo del riñón y del uréter' },
  { code: 'N20.0', desc: 'Cálculo del riñón (nefrolitiasis)' },
  { code: 'N20.1', desc: 'Cálculo del uréter' },
  { code: 'N21', desc: 'Cálculo de las vías urinarias inferiores' },
  { code: 'N23', desc: 'Cólico renal, no especificado' },
  { code: 'N28', desc: 'Otros trastornos del riñón y del uréter' },
  { code: 'N30', desc: 'Cistitis' },
  { code: 'N30.0', desc: 'Cistitis aguda' },
  { code: 'N30.9', desc: 'Cistitis, no especificada' },
  { code: 'N34', desc: 'Uretritis y síndrome uretral' },
  { code: 'N35', desc: 'Estrechez uretral' },
  { code: 'N39', desc: 'Otros trastornos del sistema urinario' },
  { code: 'N39.0', desc: 'Infección de vías urinarias, sitio no especificado' },
  { code: 'N39.3', desc: 'Incontinencia urinaria de esfuerzo' },
  { code: 'N40', desc: 'Hiperplasia de la próstata' },
  { code: 'N41', desc: 'Enfermedades inflamatorias de la próstata' },
  { code: 'N41.0', desc: 'Prostatitis aguda' },
  { code: 'N41.1', desc: 'Prostatitis crónica' },
  { code: 'N42', desc: 'Otros trastornos de la próstata' },
  { code: 'N43', desc: 'Hidrocele y espermatocele' },
  { code: 'N44', desc: 'Torsión del testículo' },
  { code: 'N45', desc: 'Orquitis y epididimitis' },
  { code: 'N48', desc: 'Otros trastornos del pene' },
  { code: 'N50', desc: 'Otros trastornos de los órganos genitales masculinos' },
  { code: 'N52', desc: 'Disfunción eréctil masculina' },
  { code: 'N60', desc: 'Displasia mamaria benigna' },
  { code: 'N61', desc: 'Trastornos inflamatorios de la mama' },
  { code: 'N62', desc: 'Hipertrofia de la mama' },
  { code: 'N63', desc: 'Masa no especificada en la mama' },
  { code: 'N64', desc: 'Otros trastornos de la mama' },
  { code: 'N70', desc: 'Salpingitis y ooforitis' },
  { code: 'N71', desc: 'Enfermedad inflamatoria del útero, excepto del cuello uterino' },
  { code: 'N72', desc: 'Enfermedad inflamatoria del cuello uterino (cervicitis)' },
  { code: 'N73', desc: 'Otras enfermedades inflamatorias pélvicas femeninas' },
  { code: 'N75', desc: 'Enfermedades de la glándula de Bartholin' },
  { code: 'N76', desc: 'Otras afecciones inflamatorias de la vagina y de la vulva' },
  { code: 'N80', desc: 'Endometriosis' },
  { code: 'N81', desc: 'Prolapso genital femenino' },
  { code: 'N83', desc: 'Trastornos no inflamatorios del ovario, de la trompa de Falopio' },
  { code: 'N83.0', desc: 'Quiste folicular del ovario' },
  { code: 'N83.1', desc: 'Quiste del cuerpo amarillo' },
  { code: 'N83.2', desc: 'Otros quistes del ovario y los no especificados' },
  { code: 'N85', desc: 'Otros trastornos no inflamatorios del útero' },
  { code: 'N87', desc: 'Displasia del cuello uterino' },
  { code: 'N89', desc: 'Otros trastornos no inflamatorios de la vagina' },
  { code: 'N91', desc: 'Menstruación ausente, escasa o rara' },
  { code: 'N91.2', desc: 'Amenorrea, no especificada' },
  { code: 'N92', desc: 'Menstruación excesiva, frecuente o irregular' },
  { code: 'N92.6', desc: 'Menstruación irregular, no especificada' },
  { code: 'N93', desc: 'Otras hemorragias uterinas o vaginales anormales' },
  { code: 'N94', desc: 'Dolor y otras afecciones relacionadas con los órganos genitales' },
  { code: 'N94.6', desc: 'Dismenorrea, no especificada' },
  { code: 'N95', desc: 'Trastornos menopáusicos y perimenopáusicos' },
  { code: 'N95.1', desc: 'Estados menopáusicos y climatéricos femeninos' },
  { code: 'N97', desc: 'Infertilidad femenina' },
  { code: 'N98', desc: 'Complicaciones asociadas con la fecundación artificial' },
  // ── O: Embarazo, parto y puerperio ────────────────────────────────────────
  { code: 'O00', desc: 'Embarazo ectópico' },
  { code: 'O00.1', desc: 'Embarazo tubárico' },
  { code: 'O02', desc: 'Otros productos anormales de la concepción' },
  { code: 'O03', desc: 'Aborto espontáneo' },
  { code: 'O04', desc: 'Aborto médico' },
  { code: 'O08', desc: 'Complicaciones consecutivas al aborto' },
  { code: 'O10', desc: 'Hipertensión preexistente que complica el embarazo' },
  { code: 'O11', desc: 'Trastorno hipertensivo preexistente con proteinuria sobreañadida' },
  { code: 'O12', desc: 'Edema y proteinuria gestacionales sin hipertensión' },
  { code: 'O13', desc: 'Hipertensión gestacional (inducida por el embarazo) sin proteinuria' },
  { code: 'O14', desc: 'Preeclampsia' },
  { code: 'O14.0', desc: 'Preeclampsia moderada' },
  { code: 'O14.1', desc: 'Preeclampsia grave' },
  { code: 'O15', desc: 'Eclampsia' },
  { code: 'O20', desc: 'Hemorragia precoz del embarazo' },
  { code: 'O21', desc: 'Vómitos excesivos en el embarazo (hiperémesis gravídica)' },
  { code: 'O23', desc: 'Infecciones de vías urinarias en el embarazo' },
  { code: 'O24', desc: 'Diabetes mellitus en el embarazo' },
  { code: 'O25', desc: 'Desnutrición en el embarazo' },
  { code: 'O26', desc: 'Atención a la madre por otras afecciones predominantemente relacionadas' },
  { code: 'O30', desc: 'Embarazo múltiple' },
  { code: 'O34', desc: 'Atención materna por anormalidades conocidas o presuntas del órgano pélvico' },
  { code: 'O36', desc: 'Atención materna por otros problemas fetales conocidos o presuntos' },
  { code: 'O42', desc: 'Ruptura prematura de las membranas' },
  { code: 'O45', desc: 'Desprendimiento prematuro de placenta' },
  { code: 'O48', desc: 'Embarazo prolongado' },
  { code: 'O60', desc: 'Parto pretérmino' },
  { code: 'O62', desc: 'Anomalías de la dinámica del parto' },
  { code: 'O63', desc: 'Parto prolongado' },
  { code: 'O69', desc: 'Complicaciones del trabajo de parto y del parto debidas al cordón umbilical' },
  { code: 'O80', desc: 'Parto único espontáneo' },
  { code: 'O82', desc: 'Parto único por cesárea' },
  { code: 'O85', desc: 'Sepsis puerperal' },
  { code: 'O86', desc: 'Otras infecciones puerperales' },
  { code: 'O87', desc: 'Complicaciones venosas en el puerperio' },
  { code: 'O90', desc: 'Complicaciones del puerperio' },
  { code: 'O92', desc: 'Otros trastornos de la mama y de la lactancia asociados al parto' },
  // ── R: Síntomas y signos ──────────────────────────────────────────────────
  { code: 'R00', desc: 'Anomalías del latido cardíaco' },
  { code: 'R00.0', desc: 'Taquicardia, no especificada' },
  { code: 'R00.1', desc: 'Bradicardia, no especificada' },
  { code: 'R00.2', desc: 'Palpitaciones' },
  { code: 'R01', desc: 'Soplos y otros sonidos cardíacos' },
  { code: 'R03', desc: 'Lectura de presión arterial anormal' },
  { code: 'R04', desc: 'Hemorragia de las vías respiratorias' },
  { code: 'R04.2', desc: 'Hemoptisis' },
  { code: 'R05', desc: 'Tos' },
  { code: 'R06', desc: 'Anomalías de la respiración' },
  { code: 'R06.0', desc: 'Disnea' },
  { code: 'R06.2', desc: 'Silbidos (sibilancias)' },
  { code: 'R07', desc: 'Dolor de garganta y en el pecho' },
  { code: 'R07.0', desc: 'Dolor de garganta' },
  { code: 'R07.1', desc: 'Dolor de pecho al respirar' },
  { code: 'R07.4', desc: 'Dolor en el pecho, no especificado' },
  { code: 'R09', desc: 'Otros síntomas y signos relacionados con los sistemas circulatorio y respiratorio' },
  { code: 'R10', desc: 'Dolor abdominal y pélvico' },
  { code: 'R10.0', desc: 'Abdomen agudo' },
  { code: 'R10.4', desc: 'Otros dolores abdominales' },
  { code: 'R11', desc: 'Náuseas y vómitos' },
  { code: 'R12', desc: 'Pirosis (acidez)' },
  { code: 'R13', desc: 'Disfagia' },
  { code: 'R14', desc: 'Flatulencia y afecciones afines' },
  { code: 'R15', desc: 'Incontinencia fecal' },
  { code: 'R17', desc: 'Ictericia no especificada' },
  { code: 'R19', desc: 'Otros síntomas y signos relacionados con los aparatos digestivo y abdomen' },
  { code: 'R20', desc: 'Trastornos de la sensibilidad cutánea' },
  { code: 'R21', desc: 'Sarpullido y otras erupciones cutáneas no específicas' },
  { code: 'R22', desc: 'Tumefacción, masa o bulto localizados en la piel y tejido subcutáneo' },
  { code: 'R23', desc: 'Otros cambios en la piel' },
  { code: 'R25', desc: 'Movimientos involuntarios anormales' },
  { code: 'R26', desc: 'Anomalías de la marcha y de la movilidad' },
  { code: 'R27', desc: 'Otras falta de coordinación' },
  { code: 'R29', desc: 'Otros síntomas y signos relacionados con los sistemas nervioso y musculoesquelético' },
  { code: 'R30', desc: 'Dolor asociado con la micción' },
  { code: 'R31', desc: 'Hematuria' },
  { code: 'R32', desc: 'Incontinencia urinaria no especificada' },
  { code: 'R33', desc: 'Retención urinaria' },
  { code: 'R35', desc: 'Poliuria' },
  { code: 'R39', desc: 'Otros síntomas y signos relacionados con el aparato urinario' },
  { code: 'R40', desc: 'Somnolencia, estupor y coma' },
  { code: 'R41', desc: 'Otros síntomas y signos relacionados con las funciones cognoscitivas y la conciencia' },
  { code: 'R42', desc: 'Mareo y desvanecimiento' },
  { code: 'R43', desc: 'Trastornos del olfato y del gusto' },
  { code: 'R44', desc: 'Otros síntomas y signos relacionados con las sensaciones y percepciones generales' },
  { code: 'R45', desc: 'Síntomas y signos relacionados con el estado emocional' },
  { code: 'R47', desc: 'Trastornos del habla' },
  { code: 'R49', desc: 'Trastornos de la voz' },
  { code: 'R50', desc: 'Fiebre de otro origen y de origen desconocido' },
  { code: 'R50.9', desc: 'Fiebre, no especificada' },
  { code: 'R51', desc: 'Cefalea' },
  { code: 'R52', desc: 'Dolor, no clasificado en otra parte' },
  { code: 'R52.9', desc: 'Dolor, no especificado' },
  { code: 'R53', desc: 'Malestar y fatiga' },
  { code: 'R54', desc: 'Senilidad' },
  { code: 'R55', desc: 'Síncope y colapso' },
  { code: 'R56', desc: 'Convulsiones, no clasificadas en otra parte' },
  { code: 'R57', desc: 'Choque, no clasificado en otra parte' },
  { code: 'R58', desc: 'Hemorragia, no clasificada en otra parte' },
  { code: 'R59', desc: 'Adenomegalias (ganglios linfáticos agrandados)' },
  { code: 'R60', desc: 'Edema, no clasificado en otra parte' },
  { code: 'R61', desc: 'Hiperhidrosis' },
  { code: 'R62', desc: 'Falta del desarrollo fisiológico normal esperado' },
  { code: 'R63', desc: 'Síntomas y signos relacionados con la ingestión de alimentos y líquidos' },
  { code: 'R63.0', desc: 'Anorexia' },
  { code: 'R63.1', desc: 'Polidipsia' },
  { code: 'R63.4', desc: 'Pérdida anormal de peso' },
  { code: 'R63.5', desc: 'Aumento anormal de peso' },
  { code: 'R64', desc: 'Caquexia' },
  { code: 'R65', desc: 'Síndrome de respuesta inflamatoria sistémica (SRIS)' },
  { code: 'R68', desc: 'Otros síntomas y signos generales especificados' },
  { code: 'R70', desc: 'Velocidad de sedimentación globular elevada e inusuales proteínas plasmáticas' },
  { code: 'R73', desc: 'Nivel elevado de glucosa en sangre' },
  { code: 'R73.0', desc: 'Prediabetes; intolerancia a la glucosa' },
  { code: 'R74', desc: 'Niveles anormales de enzimas séricas' },
  { code: 'R75', desc: 'Evidencia de laboratorio del VIH' },
  { code: 'R79', desc: 'Otros hallazgos anormales en química sanguínea' },
  { code: 'R80', desc: 'Proteinuria aislada' },
  { code: 'R82', desc: 'Otros hallazgos anormales en orina' },
  // ── S/T: Traumatismos ─────────────────────────────────────────────────────
  { code: 'S00', desc: 'Traumatismo superficial de la cabeza' },
  { code: 'S06', desc: 'Traumatismo intracraneal' },
  { code: 'S06.0', desc: 'Conmoción cerebral' },
  { code: 'S09', desc: 'Otros traumatismos de la cabeza' },
  { code: 'S10', desc: 'Traumatismo superficial del cuello' },
  { code: 'S13', desc: 'Luxación, esguince de articulaciones y ligamentos del cuello' },
  { code: 'S20', desc: 'Traumatismo superficial del tórax' },
  { code: 'S22', desc: 'Fractura de costilla, esternón y columna torácica' },
  { code: 'S30', desc: 'Traumatismo superficial del abdomen, dorso y pelvis' },
  { code: 'S32', desc: 'Fractura de la columna lumbar y de la pelvis' },
  { code: 'S40', desc: 'Traumatismo superficial del hombro y del brazo' },
  { code: 'S42', desc: 'Fractura del hombro y del brazo' },
  { code: 'S42.0', desc: 'Fractura de la clavícula' },
  { code: 'S50', desc: 'Traumatismo superficial del antebrazo' },
  { code: 'S52', desc: 'Fractura del antebrazo' },
  { code: 'S60', desc: 'Traumatismo superficial de la muñeca y de la mano' },
  { code: 'S62', desc: 'Fractura a nivel de la muñeca y de la mano' },
  { code: 'S70', desc: 'Traumatismo superficial de la cadera y del muslo' },
  { code: 'S72', desc: 'Fractura del fémur' },
  { code: 'S72.0', desc: 'Fractura del cuello del fémur (cadera)' },
  { code: 'S80', desc: 'Traumatismo superficial de la pierna' },
  { code: 'S82', desc: 'Fractura de la pierna, inclusive el tobillo' },
  { code: 'S90', desc: 'Traumatismo superficial del tobillo y del pie' },
  { code: 'S93', desc: 'Luxación y esguince de articulaciones del tobillo y del pie' },
  { code: 'T14', desc: 'Traumatismo de región del cuerpo no especificada' },
  { code: 'T36', desc: 'Envenenamiento por antibióticos sistémicos' },
  { code: 'T39', desc: 'Envenenamiento por analgésicos no narcóticos' },
  { code: 'T45', desc: 'Envenenamiento por agentes que actúan principalmente sobre sangre' },
  { code: 'T50', desc: 'Envenenamiento por diuréticos y otras drogas y medicamentos' },
  { code: 'T56', desc: 'Efectos tóxicos de metales' },
  { code: 'T65', desc: 'Efectos tóxicos de otras sustancias' },
  { code: 'T78', desc: 'Efectos adversos no clasificados en otra parte' },
  { code: 'T78.0', desc: 'Shock anafiláctico debido a reacción adversa a alimentos' },
  { code: 'T78.1', desc: 'Otras reacciones adversas a alimentos' },
  { code: 'T78.4', desc: 'Alergia, no especificada' },
  // ── Z: Factores que influyen en el estado de salud ─────────────────────────
  { code: 'Z00', desc: 'Examen general e investigación de personas sin quejas ni diagnóstico' },
  { code: 'Z00.0', desc: 'Examen médico general' },
  { code: 'Z01', desc: 'Otros exámenes de personas sin quejas ni diagnóstico notificado' },
  { code: 'Z03', desc: 'Examen médico y observación de personas sin necesidad de atención médica' },
  { code: 'Z04', desc: 'Examen y observación por otras razones' },
  { code: 'Z08', desc: 'Examen de seguimiento después de tratamiento por tumor maligno' },
  { code: 'Z09', desc: 'Examen de seguimiento después de tratamiento de otras afecciones' },
  { code: 'Z11', desc: 'Examen de detección de enfermedades infecciosas y parasitarias' },
  { code: 'Z12', desc: 'Examen de detección de tumores' },
  { code: 'Z13', desc: 'Examen de detección de otras enfermedades y trastornos' },
  { code: 'Z20', desc: 'Contacto y exposición a enfermedades contagiosas' },
  { code: 'Z23', desc: 'Necesidad de inmunización contra enfermedades bacterianas únicas' },
  { code: 'Z25', desc: 'Necesidad de inmunización contra otras enfermedades virales únicas' },
  { code: 'Z29', desc: 'Necesidad de otras medidas profilácticas' },
  { code: 'Z30', desc: 'Anticoncepción' },
  { code: 'Z34', desc: 'Supervisión de embarazo normal' },
  { code: 'Z35', desc: 'Supervisión de embarazo de alto riesgo' },
  { code: 'Z36', desc: 'Examen prenatal de detección' },
  { code: 'Z37', desc: 'Resultado del parto' },
  { code: 'Z39', desc: 'Atención y examen del postparto' },
  { code: 'Z51', desc: 'Atención médica de otro tipo' },
  { code: 'Z54', desc: 'Convalecencia' },
  { code: 'Z71', desc: 'Personas que acuden a los servicios de salud para consultas' },
  { code: 'Z76', desc: 'Personas que tienen contacto con los servicios de salud en otras circunstancias' },
  { code: 'Z80', desc: 'Historia familiar de tumor maligno' },
  { code: 'Z82', desc: 'Historia familiar de ciertas incapacidades y enfermedades crónicas' },
  { code: 'Z83', desc: 'Historia familiar de otras enfermedades específicas' },
  { code: 'Z84', desc: 'Historia familiar de otras afecciones' },
  { code: 'Z85', desc: 'Historia personal de tumor maligno' },
  { code: 'Z87', desc: 'Historia personal de otras enfermedades y afecciones' },
  { code: 'Z88', desc: 'Historia personal de alergia a drogas' },
  { code: 'Z91', desc: 'Historia personal de factores de riesgo' },
  { code: 'Z96', desc: 'Presencia de implantes e injertos funcionales' },
]

export function searchCie10(query: string, limit = 20): Cie10Code[] {
  const q = query.trim().toLowerCase()
  if (!q) return []

  const results: Array<{ code: Cie10Code; score: number }> = []

  for (const entry of CIE10_CODES) {
    const codeL = entry.code.toLowerCase()
    const descL = entry.desc.toLowerCase()

    let score = 0

    if (codeL === q) {
      score = 100
    } else if (codeL.startsWith(q)) {
      score = 90
    } else if (descL.startsWith(q)) {
      score = 80
    } else if (descL.includes(q)) {
      score = 60
    } else if (codeL.includes(q)) {
      score = 50
    } else {
      // Word-by-word matching for multi-word queries
      const words = q.split(/\s+/).filter(Boolean)
      if (words.length > 1) {
        const matchCount = words.filter(w => descL.includes(w)).length
        if (matchCount === words.length) score = 55
        else if (matchCount > 0) score = 30 * (matchCount / words.length)
      }
    }

    if (score > 0) {
      results.push({ code: entry, score })
    }
  }

  return results
    .sort((a, b) => b.score - a.score)
    .slice(0, limit)
    .map(r => r.code)
}
