// Run: npx ts-node --project tsconfig.json scripts/seed-cnmb.ts
// Source: CNMB 11va Revisión 2022 — CONASA / Comisión Nacional de Medicamentos e Insumos
// Entries: 469

import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const CNMB_DATA = [
  { codigoAtc: 'A02BC01', dci: 'Omeprazol', concentracion: '10 mg/5 mL', formaFarmaceutica: 'Sólido parenteral', nivel: 1, activo: true },
  { codigoAtc: 'A03BA01', dci: 'Atropina', concentracion: '1 mg/mL', formaFarmaceutica: 'Líquido parenteral', nivel: 1, activo: true },
  { codigoAtc: 'A03FA01', dci: 'Metoclopramida', concentracion: '10 mg', formaFarmaceutica: 'Sólido oral', nivel: 1, activo: true },
  { codigoAtc: 'A04AA01', dci: 'Ondansetrón', concentracion: '4 mg', formaFarmaceutica: 'Sólido oral', nivel: 1, activo: true },
  { codigoAtc: 'A04AD12', dci: 'Aprepitant', concentracion: '80 mg', formaFarmaceutica: 'Sólido oral', nivel: 2, activo: true },
  { codigoAtc: 'A06AD11', dci: 'Lactulosa', concentracion: '65 %', formaFarmaceutica: 'Líquido oral', nivel: 1, activo: true },
  { codigoAtc: 'A06AD65', dci: 'Lactulosa', concentracion: null, formaFarmaceutica: 'Sólido oral', nivel: 1, activo: true },
  { codigoAtc: 'A06AG04', dci: 'Glicerol', concentracion: '0,88 g - 3 g', formaFarmaceutica: 'Sólido rectal', nivel: 1, activo: true },
  { codigoAtc: 'A07AA02', dci: 'Nistatina', concentracion: '100.000 UI/mL', formaFarmaceutica: 'Líquido oral', nivel: 1, activo: true },
  { codigoAtc: 'A07BA01', dci: 'Carbón medicinal', concentracion: null, formaFarmaceutica: 'Sólido oral', nivel: 1, activo: true },
  { codigoAtc: 'A07DA03', dci: 'Loperamida', concentracion: '2 mg', formaFarmaceutica: 'Sólido oral', nivel: 1, activo: true },
  { codigoAtc: 'A07EC01', dci: 'Sulfasalazina', concentracion: '500 mg', formaFarmaceutica: 'Sólido oral', nivel: 2, activo: true },
  { codigoAtc: 'A07EC02', dci: 'Mesalazina', concentracion: '1 g', formaFarmaceutica: 'Líquido rectal', nivel: 2, activo: true },
  { codigoAtc: 'A10AB04', dci: 'Insulina Ultrarápida', concentracion: '100 UI/mL', formaFarmaceutica: 'Líquido parenteral', nivel: 2, activo: true },
  { codigoAtc: 'A10AB05', dci: 'Insulina Ultrarápida', concentracion: '100 UI/mL', formaFarmaceutica: 'Líquido parenteral', nivel: 1, activo: true },
  { codigoAtc: 'A10AE04', dci: 'Insulina Glargina', concentracion: '100 UI/mL', formaFarmaceutica: 'Líquido parenteral', nivel: 1, activo: true },
  { codigoAtc: 'A10BA02', dci: 'Metformina', concentracion: '500 mg - 1000 mg', formaFarmaceutica: 'Sólido oral', nivel: 1, activo: true },
  { codigoAtc: 'A10BB09', dci: 'Gliclazida', concentracion: '30 mg', formaFarmaceutica: null, nivel: 1, activo: true },
  { codigoAtc: 'A10BK01', dci: 'Dapagliflozina', concentracion: '10 mg', formaFarmaceutica: 'Sólido oral', nivel: 2, activo: true },
  { codigoAtc: 'A10BK03', dci: 'Empagliflozina', concentracion: '10 mg', formaFarmaceutica: 'Sólido oral', nivel: 2, activo: true },
  { codigoAtc: 'A11AA03', dci: 'Zinc', concentracion: '8 mg/5 mL', formaFarmaceutica: 'líquido oral', nivel: 1, activo: true },
  { codigoAtc: 'A11CA01', dci: 'Retinol', concentracion: '50.000 UI', formaFarmaceutica: 'Sólido oral', nivel: 1, activo: true },
  { codigoAtc: 'A11CC04', dci: 'Calcitriol', concentracion: '0,5 mcg', formaFarmaceutica: 'Sólido oral', nivel: 2, activo: true },
  { codigoAtc: 'A11DA01', dci: 'Tiamina', concentracion: '50 mg', formaFarmaceutica: 'Sólido oral', nivel: 1, activo: true },
  { codigoAtc: 'A11GA01', dci: 'Ácido ascórbico', concentracion: '100 mg/mL', formaFarmaceutica: 'Líquido parenteral', nivel: 2, activo: true },
  { codigoAtc: 'A11HA02', dci: 'Piridoxina', concentracion: '100 mg', formaFarmaceutica: 'Sólido oral', nivel: 1, activo: true },
  { codigoAtc: 'A12AA03', dci: 'Gluconato de calcio', concentracion: '10 %', formaFarmaceutica: 'Líquido parenteral', nivel: 1, activo: true },
  { codigoAtc: 'A12AA04', dci: 'Carbonato de calcio', concentracion: '500 mg', formaFarmaceutica: 'Sólido oral', nivel: 1, activo: true },
  { codigoAtc: 'A12CB01', dci: 'Sulfato de Zinc', concentracion: '20 mg', formaFarmaceutica: 'Sólido oral', nivel: 1, activo: true },
  { codigoAtc: 'B01AA03', dci: 'Warfarina', concentracion: '1 mg - 5 mg', formaFarmaceutica: 'Sólido oral', nivel: 1, activo: true },
  { codigoAtc: 'B01AB01', dci: 'Heparina', concentracion: '5.000 UI/mL', formaFarmaceutica: 'Líquido parenteral', nivel: 2, activo: true },
  { codigoAtc: 'B01AB05', dci: 'Enoxaparina', concentracion: '20 mg - 100 mg', formaFarmaceutica: 'Líquido parenteral', nivel: 1, activo: true },
  { codigoAtc: 'B01AC04', dci: 'Clopidogrel', concentracion: '75 mg', formaFarmaceutica: 'Sólido oral', nivel: 1, activo: true },
  { codigoAtc: 'B01AC06', dci: 'Ácido acetilsalicílico', concentracion: '100 mg', formaFarmaceutica: 'Sólido oral', nivel: 1, activo: true },
  { codigoAtc: 'B01AC17', dci: 'Tirofibán', concentracion: '0,25 mg/mL', formaFarmaceutica: 'Líquido parenteral', nivel: 3, activo: true },
  { codigoAtc: 'B01AC24', dci: 'Ticagrelor', concentracion: '60 mg', formaFarmaceutica: 'Sólido oral', nivel: 2, activo: true },
  { codigoAtc: 'B01AD01', dci: 'Estreptoquinasa 1´', concentracion: '500.000 UI', formaFarmaceutica: 'Sólido parenteral', nivel: 2, activo: true },
  { codigoAtc: 'B01AD02', dci: 'Alteplasa', concentracion: '50 mg', formaFarmaceutica: 'Sólido parenteral', nivel: 2, activo: true },
  { codigoAtc: 'B01AF01', dci: 'TRRivAaCroTxOa bAáLnIM', concentracion: '2,5 mg - 20 mg', formaFarmaceutica: null, nivel: 1, activo: true },
  { codigoAtc: 'B02AA02', dci: 'Ácido tranexámico', concentracion: '250 mg', formaFarmaceutica: 'Sólido oral', nivel: 2, activo: true },
  { codigoAtc: 'B02BA01', dci: 'Fitomenadiona', concentracion: '10 mg/mL', formaFarmaceutica: 'Líquido parenteral', nivel: 1, activo: true },
  { codigoAtc: 'B02BX06', dci: 'Emicizumab', concentracion: '30 mg/mL', formaFarmaceutica: 'Líquido parenteral', nivel: 3, activo: true },
  { codigoAtc: 'B03AA07', dci: 'Sulfato ferroso elemental) (equivalente', concentracion: '50 mg - 100 mg', formaFarmaceutica: 'Sólido oral', nivel: 1, activo: true },
  { codigoAtc: 'B03AE04', dci: '•Zinc •', concentracion: '300 mcg', formaFarmaceutica: 'Sólido oral', nivel: 1, activo: true },
  { codigoAtc: 'B03BB01', dci: 'Ácido fólico', concentracion: '1 mg', formaFarmaceutica: 'Sólido oral', nivel: 1, activo: true },
  { codigoAtc: 'B03XA01', dci: 'Eritropoyetina parenteral', concentracion: '2.000 UI - 30.000 UI', formaFarmaceutica: 'Sólido', nivel: 2, activo: true },
  { codigoAtc: 'B05AA01', dci: 'Albúmina Humana', concentracion: '20 %', formaFarmaceutica: 'Líquido parenteral', nivel: 2, activo: true },
  { codigoAtc: 'B05AA06', dci: 'Agentes de gelatina , 4 %', concentracion: '3,5 %', formaFarmaceutica: 'Líquido parenteral', nivel: 2, activo: true },
  { codigoAtc: 'B05BA01', dci: 'Aminoácidos', concentracion: '10 %', formaFarmaceutica: 'Líquido parenteral', nivel: 2, activo: true },
  { codigoAtc: 'B05BA02', dci: 'Emulsiones grasas', concentracion: '10 %', formaFarmaceutica: 'Líquido parenteral', nivel: 2, activo: true },
  { codigoAtc: 'B05BA03', dci: 'Emulsiones grasas', concentracion: '10 %', formaFarmaceutica: 'Líquido parenteral', nivel: 1, activo: true },
  { codigoAtc: 'B05BC01', dci: 'Manitol', concentracion: '20 %', formaFarmaceutica: 'Líquido parenteral', nivel: 2, activo: true },
  { codigoAtc: 'B05CB01', dci: 'Cloruro de sodio', concentracion: '0,9 %', formaFarmaceutica: 'Líquido parenteral', nivel: 1, activo: true },
  { codigoAtc: 'B05CB10', dci: 'Cloruro de sodio', concentracion: null, formaFarmaceutica: 'Líquido parenteral', nivel: 1, activo: true },
  { codigoAtc: 'B05XA01', dci: 'TCRloAruCrToO d AeL pIMotEaNsiToARIO Y METALBíqOuLidISoM pOarenteral 2 mEq/mL', concentracion: '2 mEq', formaFarmaceutica: null, nivel: 1, activo: true },
  { codigoAtc: 'B05XA02', dci: 'Bicarbonato de sodio 1 mEq/mL', concentracion: '8,4 %', formaFarmaceutica: 'Líquido parenteral', nivel: 1, activo: true },
  { codigoAtc: 'B05XA03', dci: 'Cloruro de sodio 3,4 mEq/mL', concentracion: '20 %', formaFarmaceutica: 'Líquido parenteral', nivel: 1, activo: true },
  { codigoAtc: 'B05XA05', dci: 'Cloruro de sodio 3,4 mEq/mL', concentracion: '20 %', formaFarmaceutica: 'Líquido parenteral', nivel: 1, activo: true },
  { codigoAtc: 'C01AA05', dci: 'Digoxina', concentracion: '50 mcg/mL', formaFarmaceutica: 'Líquido oral', nivel: 1, activo: true },
  { codigoAtc: 'C01BD01', dci: 'Amiodarona', concentracion: '200 mg', formaFarmaceutica: 'Sólido oral', nivel: 1, activo: true },
  { codigoAtc: 'C01CA03', dci: 'Norepinefrina', concentracion: '1 mg/mL', formaFarmaceutica: 'Líquido parenteral', nivel: 2, activo: true },
  { codigoAtc: 'C01CA04', dci: 'Dopamina', concentracion: '40 mg/mL', formaFarmaceutica: 'Líquido parenteral', nivel: 2, activo: true },
  { codigoAtc: 'C01CA07', dci: 'Dobutamina', concentracion: '50 mg/mL', formaFarmaceutica: 'Líquido parenteral', nivel: 2, activo: true },
  { codigoAtc: 'C01CA24', dci: 'Epinefrina', concentracion: '1 mg/mL', formaFarmaceutica: 'Líquido parenteral', nivel: 1, activo: true },
  { codigoAtc: 'C01CA26', dci: 'Efedrina', concentracion: '60 mg/mL', formaFarmaceutica: 'Líquido parenteral', nivel: 2, activo: true },
  { codigoAtc: 'C01CX08', dci: 'Levosimendán', concentracion: '2,5 mg/mL', formaFarmaceutica: 'Líquido parenteral', nivel: 2, activo: true },
  { codigoAtc: 'C01DA08', dci: 'Dinitrato de isosorbida sublingual', concentracion: '5 mg', formaFarmaceutica: 'Sólido oral', nivel: 1, activo: true },
  { codigoAtc: 'C01DA14', dci: 'Mononitrato de isosorbida', concentracion: '20 mg', formaFarmaceutica: 'Sólido oral', nivel: 1, activo: true },
  { codigoAtc: 'C01EA01', dci: 'Alprostadil', concentracion: '20 mcg/mL', formaFarmaceutica: 'Líquido parenteral', nivel: 2, activo: true },
  { codigoAtc: 'C01EB10', dci: 'Adenosina', concentracion: '3 mg/mL', formaFarmaceutica: 'Líquido parenteral', nivel: 2, activo: true },
  { codigoAtc: 'C02AB01', dci: 'Metildopa', concentracion: '250 mg', formaFarmaceutica: 'Sólido oral', nivel: 1, activo: true },
  { codigoAtc: 'C02CA04', dci: 'Doxazosina', concentracion: '2 mg', formaFarmaceutica: 'Sólido oral', nivel: 1, activo: true },
  { codigoAtc: 'C02DB02', dci: 'Hidralazina', concentracion: '50 mg', formaFarmaceutica: 'Sólido oral', nivel: 2, activo: true },
  { codigoAtc: 'C02DD01', dci: 'Nitroprusiato sódico parenteral', concentracion: '50 mg', formaFarmaceutica: 'Sólido', nivel: 2, activo: true },
  { codigoAtc: 'C03BA04', dci: 'Clortalidona', concentracion: '25 mg', formaFarmaceutica: 'Sólido oral', nivel: 1, activo: true },
  { codigoAtc: 'C03CA01', dci: 'Furosemida', concentracion: '40 mg', formaFarmaceutica: 'Sólido oral', nivel: 1, activo: true },
  { codigoAtc: 'C03DA01', dci: 'Espironolactona', concentracion: '25 mg', formaFarmaceutica: 'Sólido oral', nivel: 1, activo: true },
  { codigoAtc: 'C05BB02', dci: 'Polidocanol', concentracion: '3 %', formaFarmaceutica: 'Líquido parenteral', nivel: 2, activo: true },
  { codigoAtc: 'C07AA05', dci: 'Propranolol', concentracion: '10 mg', formaFarmaceutica: 'Sólido oral', nivel: 1, activo: true },
  { codigoAtc: 'C07AB03', dci: 'Atenolol', concentracion: '50 mg', formaFarmaceutica: 'Sólido oral', nivel: 1, activo: true },
  { codigoAtc: 'C07AG01', dci: 'Labetalol', concentracion: '200 mg', formaFarmaceutica: 'Sólido oral', nivel: 2, activo: true },
  { codigoAtc: 'C07AG02', dci: 'Carvedilol', concentracion: '6,25 mg - 25 mg', formaFarmaceutica: 'Sólido oral', nivel: 1, activo: true },
  { codigoAtc: 'C08CA01', dci: 'Amlodipina', concentracion: '5 mg', formaFarmaceutica: 'Sólido oral', nivel: 1, activo: true },
  { codigoAtc: 'C08CA05', dci: 'Nifedipina', concentracion: '10 mg', formaFarmaceutica: 'Sólido oral', nivel: 1, activo: true },
  { codigoAtc: 'C08DB01', dci: 'Diltiazem', concentracion: '60 mg', formaFarmaceutica: 'Sólido oral', nivel: 1, activo: true },
  { codigoAtc: 'C09AA02', dci: 'Enalapril', concentracion: '5 mg', formaFarmaceutica: 'Sólido oral', nivel: 1, activo: true },
  { codigoAtc: 'C09CA01', dci: 'Losartán', concentracion: '50 mg', formaFarmaceutica: 'Sólido oral', nivel: 1, activo: true },
  { codigoAtc: 'C09DB04', dci: 'Telmisartán + Amlodipino', concentracion: '40 mg', formaFarmaceutica: 'Sólido oral', nivel: 1, activo: true },
  { codigoAtc: 'C10AA01', dci: 'TSiRmAvCaTsOta AtiLnIaMENTARIO Y METASBóOlidLIoS MorOal', concentracion: '20 mg', formaFarmaceutica: null, nivel: 1, activo: true },
  { codigoAtc: 'C10AA05', dci: 'Atorvastatina ;', concentracion: '20 mg', formaFarmaceutica: 'Sólido oral', nivel: 1, activo: true },
  { codigoAtc: 'C10AB04', dci: 'Gemfibrozilo', concentracion: '600 mg', formaFarmaceutica: 'Sólido oral', nivel: 1, activo: true },
  { codigoAtc: 'D01AA20', dci: 'Zinc + Nistatina Semi cutáneo', concentracion: null, formaFarmaceutica: 'sólido', nivel: 1, activo: true },
  { codigoAtc: 'D01AC01', dci: 'Clotrimazol cutáneo', concentracion: '1 %', formaFarmaceutica: 'Líquido', nivel: 1, activo: true },
  { codigoAtc: 'D01AE15', dci: 'Terbinafina Semi cutáneo', concentracion: '1 %', formaFarmaceutica: 'sólido', nivel: 1, activo: true },
  { codigoAtc: 'D01BA01', dci: 'Griseofulvina', concentracion: '125 mg - 500 mg', formaFarmaceutica: 'Sólido oral', nivel: 1, activo: true },
  { codigoAtc: 'D01BA02', dci: 'Terbinafina', concentracion: '250 mg', formaFarmaceutica: 'Sólido oral', nivel: 1, activo: true },
  { codigoAtc: 'D02AE01', dci: 'Urea Semi cutáneo', concentracion: '5 % - 20 %', formaFarmaceutica: 'sólido', nivel: 1, activo: true },
  { codigoAtc: 'D03AX12', dci: 'Trolamina', concentracion: '0,67 %', formaFarmaceutica: 'Líquido', nivel: 2, activo: true },
  { codigoAtc: 'D04AB01', dci: 'Lidocaína cutáneo', concentracion: '10 %', formaFarmaceutica: 'Líquido', nivel: 1, activo: true },
  { codigoAtc: 'D05AX52', dci: 'Calcipotriol + Betametasona Semi cutáneo /g', concentracion: '50 mcg', formaFarmaceutica: 'sólido', nivel: 2, activo: true },
  { codigoAtc: 'D06AX01', dci: 'Ácido fusídico Semi cutáneo', concentracion: '2 %', formaFarmaceutica: 'sólido', nivel: 1, activo: true },
  { codigoAtc: 'D06BA01', dci: 'Sulfadiazina de plata Semi cutáneo', concentracion: '1 %', formaFarmaceutica: 'sólido', nivel: 1, activo: true },
  { codigoAtc: 'D07AA02', dci: 'Hidrocortisona', concentracion: '0,5 %', formaFarmaceutica: 'Líquido', nivel: 1, activo: true },
  { codigoAtc: 'D07AC01', dci: 'Betametasona', concentracion: '0,05 %', formaFarmaceutica: 'Líquido', nivel: 1, activo: true },
  { codigoAtc: 'D10AD03', dci: 'Adapaleno Semi cutáneo', concentracion: '0,1 %', formaFarmaceutica: 'sólido', nivel: 1, activo: true },
  { codigoAtc: 'D10AD04', dci: 'Isotretinoina', concentracion: '10 mg', formaFarmaceutica: 'Sólido oral', nivel: 2, activo: true },
  { codigoAtc: 'D10AE01', dci: 'Peróxido de benzoilo', concentracion: '5 %', formaFarmaceutica: 'Líquido', nivel: 1, activo: true },
  { codigoAtc: 'D10AF01', dci: 'Clindamicina cutáneo', concentracion: '1 %', formaFarmaceutica: 'Líquido', nivel: 1, activo: true },
  { codigoAtc: 'D10AF02', dci: 'Eritromicina cutáneo', concentracion: '4 %', formaFarmaceutica: 'Líquido', nivel: 1, activo: true },
  { codigoAtc: 'G01AA10', dci: 'Clindamicina', concentracion: '100 mg', formaFarmaceutica: 'Sólido vaginal', nivel: 1, activo: true },
  { codigoAtc: 'G01AF01', dci: 'Metronidazol', concentracion: '500 mg', formaFarmaceutica: 'Sólido vaginal', nivel: 1, activo: true },
  { codigoAtc: 'G01AF02', dci: 'Clotrimazol Semi', concentracion: '1 %', formaFarmaceutica: 'sólido vaginal', nivel: 1, activo: true },
  { codigoAtc: 'G02AD06', dci: 'Misoprostol', concentracion: '200 mcg', formaFarmaceutica: 'Sólido oral', nivel: 1, activo: true },
  { codigoAtc: 'G02CB03', dci: 'Cabergolina', concentracion: '0,5 mg', formaFarmaceutica: 'Sólido oral', nivel: 1, activo: true },
  { codigoAtc: 'G03AA05', dci: '/mL', concentracion: '5 mg', formaFarmaceutica: 'Líquido parenteral', nivel: 1, activo: true },
  { codigoAtc: 'G03AC03', dci: 'Levonorgestrel', concentracion: '150 mg', formaFarmaceutica: 'Sólido parenteral', nivel: 1, activo: true },
  { codigoAtc: 'G03AC03', dci: 'Levonorgestrel', concentracion: '52 mg', formaFarmaceutica: null, nivel: 2, activo: true },
  { codigoAtc: 'G03AD01', dci: 'Levonorgestrel', concentracion: '0,75 mg', formaFarmaceutica: 'Sólido oral', nivel: 1, activo: true },
  { codigoAtc: 'G03BA03', dci: 'Testosterona', concentracion: '250 mg/mL', formaFarmaceutica: 'Líquido parenteral', nivel: 2, activo: true },
  { codigoAtc: 'G03CA03', dci: 'Estradiol', concentracion: '1 mg', formaFarmaceutica: 'parche transdérmico', nivel: 2, activo: true },
  { codigoAtc: 'G03CA04', dci: 'Estriol Semi', concentracion: '0,1 %', formaFarmaceutica: 'sólido vaginal', nivel: 1, activo: true },
  { codigoAtc: 'G03DA04', dci: 'Progesterona', concentracion: '100 mg', formaFarmaceutica: 'Sólido oral', nivel: 1, activo: true },
  { codigoAtc: 'G03GB02', dci: 'Clomifeno', concentracion: '50 mg', formaFarmaceutica: 'Sólido oral', nivel: 2, activo: true },
  { codigoAtc: 'G03XB01', dci: 'Mifepristona', concentracion: '200 mg', formaFarmaceutica: 'Sólido oral', nivel: 1, activo: true },
  { codigoAtc: 'G04CA02', dci: 'Tamsulosina', concentracion: '0,4 mg', formaFarmaceutica: 'Sólido oral', nivel: 1, activo: true },
  { codigoAtc: 'G04BE03', dci: 'Sildenafilo', concentracion: '25 mg - 100 mg', formaFarmaceutica: 'Sólido oral', nivel: 3, activo: true },
  { codigoAtc: 'G04CB02', dci: 'Dutasterida', concentracion: '0,5 mg', formaFarmaceutica: 'Sólido oral', nivel: 2, activo: true },
  { codigoAtc: 'H01AB01', dci: 'Tirotropina Alfa', concentracion: '0,9 mg', formaFarmaceutica: 'Sólido parenteral', nivel: 3, activo: true },
  { codigoAtc: 'H01AC01', dci: 'Somatropina', concentracion: '5,3 mg - 20 mg', formaFarmaceutica: 'Sólido', nivel: 3, activo: true },
  { codigoAtc: 'H01BA02', dci: 'Desmopresina', concentracion: '15 mcg/mL', formaFarmaceutica: 'Líquido parenteral', nivel: 2, activo: true },
  { codigoAtc: 'H01BA04', dci: 'Terlipresina', concentracion: '0,86 mg', formaFarmaceutica: 'Sólido', nivel: 2, activo: true },
  { codigoAtc: 'H01BB02', dci: 'Oxitocina', concentracion: '10 UI/mL', formaFarmaceutica: 'Líquido parenteral', nivel: 1, activo: true },
  { codigoAtc: 'H01CB02', dci: 'Octreotida', concentracion: '20 mg', formaFarmaceutica: 'Sólido parenteral', nivel: 3, activo: true },
  { codigoAtc: 'H02AA02', dci: 'Fludrocortisona', concentracion: '0,1 mg', formaFarmaceutica: 'Sólido oral', nivel: 1, activo: true },
  { codigoAtc: 'H02AB01', dci: 'Betametasona', concentracion: '4 mg/mL', formaFarmaceutica: 'Líquido parenteral', nivel: 1, activo: true },
  { codigoAtc: 'H02AB02', dci: 'Dexametasona', concentracion: '40 mg/mL', formaFarmaceutica: 'Líquido parenteral', nivel: 1, activo: true },
  { codigoAtc: 'H02AB06', dci: 'Prednisolona', concentracion: '5 mg', formaFarmaceutica: 'Sólido oral', nivel: 1, activo: true },
  { codigoAtc: 'H02AB07', dci: 'Prednisona', concentracion: '5 mg', formaFarmaceutica: 'Sólido oral', nivel: 1, activo: true },
  { codigoAtc: 'H02AB09', dci: 'Hidrocortisona', concentracion: '5 mg - 20 mg', formaFarmaceutica: 'Sólido oral', nivel: 2, activo: true },
  { codigoAtc: 'H03AA01', dci: 'Levotiroxina sódica', concentracion: '25 mcg - 200 mcg', formaFarmaceutica: 'Sólido oral', nivel: 1, activo: true },
  { codigoAtc: 'H03BB02', dci: 'Tiamazol', concentracion: '5 mg', formaFarmaceutica: 'Sólido oral', nivel: 2, activo: true },
  { codigoAtc: 'H04AA01', dci: 'Glucagón', concentracion: '1 mg', formaFarmaceutica: 'Sólido parenteral', nivel: 1, activo: true },
  { codigoAtc: 'H05BX02', dci: 'Paricalcitol', concentracion: '5 mcg/mL', formaFarmaceutica: 'Líquido parenteral', nivel: 3, activo: true },
  { codigoAtc: 'J01AA02', dci: 'Doxiciclina', concentracion: '100 mg', formaFarmaceutica: 'Sólido oral', nivel: 1, activo: true },
  { codigoAtc: 'J01AA12', dci: 'Tigeciclina', concentracion: '50 mg', formaFarmaceutica: 'Sólido parenteral', nivel: 2, activo: true },
  { codigoAtc: 'J01CA01', dci: 'Ampicilina', concentracion: '500 mg', formaFarmaceutica: 'Sólido parenteral', nivel: 1, activo: true },
  { codigoAtc: 'J01CA04', dci: 'Amoxicilina', concentracion: '100 mg/mL', formaFarmaceutica: 'Sólido oral', nivel: 1, activo: true },
  { codigoAtc: 'J01CE08', dci: '- 2´400.000 UI', concentracion: '600.000 UI', formaFarmaceutica: 'Sólido parenteral', nivel: 1, activo: true },
  { codigoAtc: 'J01CF01', dci: 'Dicloxacilina', concentracion: '125 mg/5 mL', formaFarmaceutica: 'Sólido oral', nivel: 1, activo: true },
  { codigoAtc: 'J01CF04', dci: 'Oxacilina', concentracion: '1.000 mg', formaFarmaceutica: 'Sólido parenteral', nivel: 2, activo: true },
  { codigoAtc: 'J01CR01', dci: 'TARmApCicTiOlin AaL +IM SuElNbTaActRaImO Y METASBóOlidLIoS MpaOrenteral', concentracion: '1.000 mg', formaFarmaceutica: 'Sólido parenteral', nivel: 2, activo: true },
  { codigoAtc: 'J01CR04', dci: 'Sultamicilina', concentracion: '375 mg', formaFarmaceutica: 'Sólido oral', nivel: 1, activo: true },
  { codigoAtc: 'J01CR05', dci: 'Piperacilina + Tazobactam', concentracion: '4.000 mg', formaFarmaceutica: 'Sólido parenteral', nivel: 2, activo: true },
  { codigoAtc: 'J01DB01', dci: 'Cefalexina', concentracion: '250 mg/5 mL', formaFarmaceutica: 'Sólido oral', nivel: 1, activo: true },
  { codigoAtc: 'J01DB04', dci: 'Cefazolina K', concentracion: '1.000 mg', formaFarmaceutica: 'Sólido parenteral', nivel: 1, activo: true },
  { codigoAtc: 'J01DC02', dci: 'Cefuroxima', concentracion: '250 mg', formaFarmaceutica: 'Sólido parenteral', nivel: 1, activo: true },
  { codigoAtc: 'J01DD01', dci: 'Cefotaxima', concentracion: '1.000 mg', formaFarmaceutica: 'Sólido parenteral', nivel: 2, activo: true },
  { codigoAtc: 'J01DD02', dci: 'Ceftazidima', concentracion: '500 mg', formaFarmaceutica: 'Sólido parenteral', nivel: 2, activo: true },
  { codigoAtc: 'J01DD04', dci: 'Ceftriaxona', concentracion: '500 mg', formaFarmaceutica: 'Sólido parenteral', nivel: 1, activo: true },
  { codigoAtc: 'J01DD52', dci: 'Ceftazidima + Avibactam', concentracion: '2.000 mg', formaFarmaceutica: 'Sólido parenteral', nivel: 3, activo: true },
  { codigoAtc: 'J01DE01', dci: 'Cefepima', concentracion: '1.000 mg', formaFarmaceutica: 'Sólido parenteral', nivel: 2, activo: true },
  { codigoAtc: 'J01DH02', dci: 'Meropenem', concentracion: '500 mg', formaFarmaceutica: 'Sólido parenteral', nivel: 2, activo: true },
  { codigoAtc: 'J01DH51', dci: 'Imipenem + Cilastatina', concentracion: '500 mg', formaFarmaceutica: 'Sólido parenteral', nivel: 2, activo: true },
  { codigoAtc: 'J01EC02', dci: 'Sulfadiazina', concentracion: '500 mg', formaFarmaceutica: 'Sólido oral', nivel: 3, activo: true },
  { codigoAtc: 'J01EE01', dci: 'y Trimetoprim)', concentracion: '400 mg', formaFarmaceutica: 'Líquido oral', nivel: 1, activo: true },
  { codigoAtc: 'J01FA01', dci: 'Eritromicina', concentracion: '200 mg/5 mL', formaFarmaceutica: 'Sólido oral', nivel: 1, activo: true },
  { codigoAtc: 'J01FA02', dci: 'Espiramicina', concentracion: '000.000 UI', formaFarmaceutica: 'Sólido parenteral', nivel: 3, activo: true },
  { codigoAtc: 'J01FA09', dci: 'Claritromicina', concentracion: '125 mg/5 mL', formaFarmaceutica: 'Sólido oral', nivel: 1, activo: true },
  { codigoAtc: 'J01FA10', dci: 'Azitromicina', concentracion: '200 mg/5 mL', formaFarmaceutica: 'Sólido oral', nivel: 1, activo: true },
  { codigoAtc: 'J01FF01', dci: 'Clindamicina', concentracion: '300 mg', formaFarmaceutica: 'Sólido oral', nivel: 1, activo: true },
  { codigoAtc: 'J01GA01', dci: 'Estreptomicina', concentracion: '1.000 mg', formaFarmaceutica: 'Sólido parenteral', nivel: 1, activo: true },
  { codigoAtc: 'J01GB01', dci: 'Tobramicina', concentracion: '28 mg', formaFarmaceutica: 'Sólido', nivel: 2, activo: true },
  { codigoAtc: 'J01GB03', dci: 'Gentamicina', concentracion: '10 mg/mL - 140 mg/mL', formaFarmaceutica: 'Líquido parenteral', nivel: 1, activo: true },
  { codigoAtc: 'J01GB06', dci: 'TARmAikCaTcOin AaLIMENTARIO Y METALBíqOuLidISoM pOarenteral', concentracion: '50 mg/mL - 250 mg/mL', formaFarmaceutica: null, nivel: 2, activo: true },
  { codigoAtc: 'J01MA02', dci: 'Ciprofloxacina', concentracion: '20 mg/mL', formaFarmaceutica: 'Líquido parenteral', nivel: 1, activo: true },
  { codigoAtc: 'J01MA12', dci: 'Levofloxacina', concentracion: '250 mg', formaFarmaceutica: 'Sólido oral', nivel: 2, activo: true },
  { codigoAtc: 'J01XA01', dci: 'Vancomicina', concentracion: '500 mg', formaFarmaceutica: 'Sólido parenteral', nivel: 2, activo: true },
  { codigoAtc: 'J01XB01', dci: 'Colistina', concentracion: '100 mg', formaFarmaceutica: 'Sólido parenteral', nivel: 2, activo: true },
  { codigoAtc: 'J01XD01', dci: 'Metronidazol K', concentracion: '5 mg/mL', formaFarmaceutica: 'Líquido parenteral', nivel: 1, activo: true },
  { codigoAtc: 'J01XE01', dci: 'Nitrofurantoína', concentracion: '100 mg', formaFarmaceutica: 'Sólido oral', nivel: 1, activo: true },
  { codigoAtc: 'J01XX01', dci: 'Fosfomicina Trometanol', concentracion: '250 mg/5 mL', formaFarmaceutica: 'Líquido parenteral', nivel: 1, activo: true },
  { codigoAtc: 'J01XX08', dci: 'Linezolid', concentracion: '600 mg', formaFarmaceutica: 'Sólido oral', nivel: 2, activo: true },
  { codigoAtc: 'J02AA01', dci: 'Amfotericina B', concentracion: '50 mg', formaFarmaceutica: 'Sólido parenteral', nivel: 2, activo: true },
  { codigoAtc: 'J02AA01', dci: 'parenteral', concentracion: '50 mg', formaFarmaceutica: 'Sólido', nivel: 2, activo: true },
  { codigoAtc: 'J02AC01', dci: 'Fluconazol', concentracion: '10 mg/mL', formaFarmaceutica: 'Líquido oral', nivel: 1, activo: true },
  { codigoAtc: 'J02AC02', dci: 'Itraconazol', concentracion: '100 mg', formaFarmaceutica: 'Sólido oral', nivel: 2, activo: true },
  { codigoAtc: 'J02AC03', dci: 'Voriconazol rev', concentracion: '200 mg', formaFarmaceutica: 'Sólido parenteral', nivel: 2, activo: true },
  { codigoAtc: 'J02AX04', dci: 'Caspofungina', concentracion: '50 mg', formaFarmaceutica: 'Sólido parenteral', nivel: 2, activo: true },
  { codigoAtc: 'J04AB01', dci: 'TCRicAloCsTeOri nAaLIMENTARIO Y METASBóOlidLIoS MorOal', concentracion: '100 mg/5 mL', formaFarmaceutica: 'Líquido oral', nivel: 1, activo: true },
  { codigoAtc: 'J04AB02', dci: 'Rifampicina', concentracion: '300 mg', formaFarmaceutica: 'Sólido oral', nivel: 1, activo: true },
  { codigoAtc: 'J04AB30', dci: 'Capreomicina', concentracion: '1.000 mg', formaFarmaceutica: 'Sólido parenteral', nivel: 1, activo: true },
  { codigoAtc: 'J04AC01', dci: 'Isoniazida', concentracion: '100 mg', formaFarmaceutica: 'Sólido oral', nivel: 1, activo: true },
  { codigoAtc: 'J04AD03', dci: 'Etionamida', concentracion: '250 mg', formaFarmaceutica: 'Sólido oral', nivel: 1, activo: true },
  { codigoAtc: 'J04AK01', dci: 'Pirazinamida', concentracion: '500 mg', formaFarmaceutica: 'Sólido oral', nivel: 1, activo: true },
  { codigoAtc: 'J04AK02', dci: 'Etambutol', concentracion: '400 mg', formaFarmaceutica: 'Sólido oral', nivel: 1, activo: true },
  { codigoAtc: 'J04AK05', dci: 'Bedaquilina', concentracion: '100 mg', formaFarmaceutica: 'Sólido oral', nivel: 1, activo: true },
  { codigoAtc: 'J04AK06', dci: 'Delamanida', concentracion: '50 mg', formaFarmaceutica: 'Sólido oral', nivel: 1, activo: true },
  { codigoAtc: 'J04AK08', dci: 'Pretomanida', concentracion: '200 mg', formaFarmaceutica: 'Sólido oral', nivel: 1, activo: true },
  { codigoAtc: 'J04AM02', dci: 'Rifampicina + Isoniazida', concentracion: '300 mg', formaFarmaceutica: 'Sólido oral', nivel: 1, activo: true },
  { codigoAtc: 'J04AM03', dci: 'Etambutol + Isoniazida', concentracion: '400 mg', formaFarmaceutica: 'Sólido oral', nivel: 1, activo: true },
  { codigoAtc: 'J04BA01', dci: 'Clofazimina', concentracion: '100 mg', formaFarmaceutica: 'Sólido oral', nivel: 2, activo: true },
  { codigoAtc: 'J04BA02', dci: 'Dapsona', concentracion: '100 mg', formaFarmaceutica: 'Sólido oral', nivel: 2, activo: true },
  { codigoAtc: 'J05AB01', dci: 'Aciclovir', concentracion: '200 mg - 800 mg', formaFarmaceutica: 'Sólido parenteral', nivel: 1, activo: true },
  { codigoAtc: 'J05AB14', dci: 'Valganciclovir', concentracion: '450 mg', formaFarmaceutica: 'Sólido oral', nivel: 2, activo: true },
  { codigoAtc: 'J05AE03', dci: 'Ritonavir', concentracion: '100 mg', formaFarmaceutica: 'Sólido oral', nivel: 1, activo: true },
  { codigoAtc: 'J05AE08', dci: 'Atazanavir', concentracion: '150 mg', formaFarmaceutica: 'Sólido oral', nivel: 1, activo: true },
  { codigoAtc: 'J05AE10', dci: 'Darunavir', concentracion: '400 mg - 800 mg', formaFarmaceutica: 'Sólido oral', nivel: 1, activo: true },
  { codigoAtc: 'J05AF01', dci: 'Zidovudina', concentracion: '10 mg/mL', formaFarmaceutica: 'Líquido parenteral', nivel: 1, activo: true },
  { codigoAtc: 'J05AF05', dci: 'Lamivudina', concentracion: '10 mg/mL', formaFarmaceutica: 'Líquido oral', nivel: 1, activo: true },
  { codigoAtc: 'J05AF06', dci: 'Abacavir', concentracion: '300 mg', formaFarmaceutica: 'Sólido oral', nivel: 1, activo: true },
  { codigoAtc: 'J05AF07', dci: 'Tenofovir disoproxil fumarato', concentracion: '10 mg/mL', formaFarmaceutica: 'Líquido oral', nivel: 1, activo: true },
  { codigoAtc: 'J05AF09', dci: 'Emtricitabina', concentracion: '200 mg', formaFarmaceutica: 'Sólido oral', nivel: 1, activo: true },
  { codigoAtc: 'J05AG01', dci: 'Nevirapina', concentracion: '30 mg/mL', formaFarmaceutica: 'Líquido oral', nivel: 1, activo: true },
  { codigoAtc: 'J05AG03', dci: 'Efavirenz', concentracion: '50 mg - 600 mg', formaFarmaceutica: 'Sólido oral', nivel: 1, activo: true },
  { codigoAtc: 'J05AG04', dci: 'Etravirina', concentracion: '100 mg', formaFarmaceutica: 'Sólido oral', nivel: 1, activo: true },
  { codigoAtc: 'J05AH02', dci: 'Oseltamivir', concentracion: '75 mg', formaFarmaceutica: 'Sólido oral', nivel: 1, activo: true },
  { codigoAtc: 'J05AJ01', dci: 'TRRalAteCgTrOav AirLIMENTARIO Y METASBóOlidLIoS MorOal', concentracion: '400 mg', formaFarmaceutica: null, nivel: 1, activo: true },
  { codigoAtc: 'J05AJ03', dci: 'Dolutegravir sódico', concentracion: '50 mg', formaFarmaceutica: 'Sólido oral', nivel: 2, activo: true },
  { codigoAtc: 'J05AP01', dci: 'Ribavirina', concentracion: '200 mg - 600 mg', formaFarmaceutica: 'Sólido oral', nivel: 2, activo: true },
  { codigoAtc: 'J05AP08', dci: 'Sofosbuvir', concentracion: '400 mg', formaFarmaceutica: 'Sólido oral', nivel: 2, activo: true },
  { codigoAtc: 'J05AP51', dci: 'Ledipasvir + Sofosbuvir', concentracion: null, formaFarmaceutica: 'Sólido oral', nivel: 3, activo: true },
  { codigoAtc: 'J05AP55', dci: 'Sofosbuvir + Velpatasvir', concentracion: '400 mg', formaFarmaceutica: 'Sólido oral', nivel: 3, activo: true },
  { codigoAtc: 'J05AP57', dci: 'Glecaprevir + Pibrentasvir de', concentracion: '100 mg', formaFarmaceutica: 'Sólido oral', nivel: 3, activo: true },
  { codigoAtc: 'J05AR01', dci: 'Zidovudina + Lamivudina', concentracion: '300 mg', formaFarmaceutica: 'Sólido oral', nivel: 1, activo: true },
  { codigoAtc: 'J05AR02', dci: 'Lamivudina + Abacavir', concentracion: '300 mg', formaFarmaceutica: 'Sólido oral', nivel: 1, activo: true },
  { codigoAtc: 'J05AR06', dci: 'fumarato+ Emtricitabina', concentracion: '20 mg/mL', formaFarmaceutica: 'Líquido oral', nivel: 1, activo: true },
  { codigoAtc: 'J05AR10', dci: 'Lopinavir + Ritonavir y', concentracion: '100 mg', formaFarmaceutica: 'Sólido oral', nivel: 1, activo: true },
  { codigoAtc: 'J06AA01', dci: 'Diftérica antitoxina', concentracion: null, formaFarmaceutica: 'Líquido parenteral', nivel: 1, activo: true },
  { codigoAtc: 'J06AA02', dci: 'Tetánica antitoxina', concentracion: null, formaFarmaceutica: 'Líquido parenteral', nivel: 1, activo: true },
  { codigoAtc: 'J06AA03', dci: 'Suero antiofídico polivalente parenteral', concentracion: null, formaFarmaceutica: 'Sólido', nivel: 1, activo: true },
  { codigoAtc: 'J06BA02', dci: 'normal para administración', concentracion: '50 mg/mL - 200 mg/mL', formaFarmaceutica: 'Líquido parenteral', nivel: 2, activo: true },
  { codigoAtc: 'J06BB01', dci: 'Inmunoglobulina anti D', concentracion: '625 UI - 1500 UI', formaFarmaceutica: 'Líquido parenteral', nivel: 2, activo: true },
  { codigoAtc: 'J06BB02', dci: 'Inmunoglobulina antitetánica parenteral/ - 500 Ul', concentracion: '200 UI', formaFarmaceutica: 'Sólido', nivel: 1, activo: true },
  { codigoAtc: 'J06BB04', dci: 'Inmunoglobulina antitetánica parenteral/ - 500 Ul', concentracion: '20 mcg/mL', formaFarmaceutica: 'Líquido parenteral', nivel: 1, activo: true },
  { codigoAtc: 'J06BB05', dci: 'Inmunoglobulina antirrábica - 1500Ul/mL', concentracion: '150 UI/mL', formaFarmaceutica: 'Líquido parenteral', nivel: 1, activo: true },
  { codigoAtc: 'J07AH02', dci: 'Vacuna antimeningococo parenteral', concentracion: null, formaFarmaceutica: 'Sólido', nivel: 1, activo: true },
  { codigoAtc: 'J07AJ52', dci: 'Vacuna pertussis', concentracion: null, formaFarmaceutica: 'Líquido parenteral', nivel: 1, activo: true },
  { codigoAtc: 'J07AM01', dci: 'Toxoide tetánico > /0,5 mL', concentracion: '40 UI', formaFarmaceutica: 'Líquido parenteral', nivel: 1, activo: true },
  { codigoAtc: 'J07AM51', dci: 'combinaciones con toxoide', concentracion: null, formaFarmaceutica: 'Líquido parenteral', nivel: 1, activo: true },
  { codigoAtc: 'J07AN01', dci: 'Vacuna BCG antituberculosa', concentracion: null, formaFarmaceutica: 'Sólido parenteral', nivel: 1, activo: true },
  { codigoAtc: 'J07BB02', dci: 'inactivado y separado, o', concentracion: null, formaFarmaceutica: 'Líquido parenteral', nivel: 1, activo: true },
  { codigoAtc: 'J07BC01', dci: 'Vacuna antihepatitis B', concentracion: null, formaFarmaceutica: 'Líquido parenteral', nivel: 1, activo: true },
  { codigoAtc: 'J07BC02', dci: 'Vacuna antihepatitis A', concentracion: null, formaFarmaceutica: 'Líquido parenteral', nivel: 1, activo: true },
  { codigoAtc: 'J07BD53', dci: 'atenuado combinado con la', concentracion: null, formaFarmaceutica: 'Sólido parenteral', nivel: 1, activo: true },
  { codigoAtc: 'J07BF03', dci: 'inactivado, virus entero', concentracion: null, formaFarmaceutica: 'Líquido parenteral', nivel: 1, activo: true },
  { codigoAtc: 'J07BF04', dci: 'vivo atenuado, bivalente', concentracion: null, formaFarmaceutica: 'Líquido oral', nivel: 1, activo: true },
  { codigoAtc: 'J07BG01', dci: 'parenteral', concentracion: null, formaFarmaceutica: 'Sólido', nivel: 1, activo: true },
  { codigoAtc: 'J07CA11', dci: 'parenteral', concentracion: null, formaFarmaceutica: 'Sólido', nivel: 1, activo: true },
  { codigoAtc: 'L01AA01', dci: 'Ciclofosfamida', concentracion: '500 mg', formaFarmaceutica: 'Sólido parenteral', nivel: 2, activo: true },
  { codigoAtc: 'L01AA02', dci: 'Clorambucilo', concentracion: '2 mg', formaFarmaceutica: 'Sólido oral', nivel: 2, activo: true },
  { codigoAtc: 'L01AA03', dci: 'Melfalán', concentracion: '50 mg', formaFarmaceutica: 'Sólido parenteral', nivel: 3, activo: true },
  { codigoAtc: 'L01AA06', dci: 'Ifosfamida', concentracion: '1 g', formaFarmaceutica: 'Sólido parenteral', nivel: 2, activo: true },
  { codigoAtc: 'L01AA09', dci: 'Bendamustina', concentracion: '25 mg', formaFarmaceutica: 'Sólido parenteral', nivel: 2, activo: true },
  { codigoAtc: 'L01AX03', dci: 'Temozolomida', concentracion: '20 mg - 250 mg', formaFarmaceutica: 'Sólido oral', nivel: 2, activo: true },
  { codigoAtc: 'L01AX04', dci: 'Dacarbazina', concentracion: '100 mg', formaFarmaceutica: 'Sólido parenteral', nivel: 2, activo: true },
  { codigoAtc: 'L01BA01', dci: 'Metotrexato', concentracion: '2,5 mg', formaFarmaceutica: 'Sólido parenteral', nivel: 1, activo: true },
  { codigoAtc: 'L01BA04', dci: 'Pemetrexed', concentracion: '500 mg', formaFarmaceutica: 'Sólido parenteral', nivel: 2, activo: true },
  { codigoAtc: 'L01BB02', dci: 'Mercaptopurina', concentracion: '50 mg', formaFarmaceutica: 'Sólido oral', nivel: 2, activo: true },
  { codigoAtc: 'L01BB03', dci: 'Tioguanina', concentracion: '40 mg', formaFarmaceutica: 'Sólido oral', nivel: 2, activo: true },
  { codigoAtc: 'L01BB05', dci: 'Fludarabina', concentracion: '50 mg', formaFarmaceutica: 'Sólido parenteral', nivel: 2, activo: true },
  { codigoAtc: 'L01BC01', dci: 'Citarabina', concentracion: '25 mg/mL - 50 mg/mL', formaFarmaceutica: 'Líquido parenteral', nivel: 2, activo: true },
  { codigoAtc: 'L01BC02', dci: 'Fluoruracilo Semi cutáneo', concentracion: '5 %', formaFarmaceutica: 'sólido', nivel: 2, activo: true },
  { codigoAtc: 'L01BC05', dci: 'Gemcitabina', concentracion: '200 mg', formaFarmaceutica: 'Sólido parenteral', nivel: 2, activo: true },
  { codigoAtc: 'L01BC06', dci: 'Capecitabina', concentracion: '500 mg', formaFarmaceutica: 'Sólido oral', nivel: 2, activo: true },
  { codigoAtc: 'L01BC07', dci: 'Azacitidina', concentracion: '100 mg', formaFarmaceutica: 'Sólido parenteral', nivel: 2, activo: true },
  { codigoAtc: 'L01CA01', dci: 'Vinblastina', concentracion: '10 mg/mL', formaFarmaceutica: 'Líquido parenteral', nivel: 2, activo: true },
  { codigoAtc: 'L01CA02', dci: 'Vincristina sulfato', concentracion: '1 mg/mL', formaFarmaceutica: 'Sólido Parenteral', nivel: 2, activo: true },
  { codigoAtc: 'L01CA04', dci: 'TVRinAoCrTeOlb iAnLaI', concentracion: '10 mg/mL', formaFarmaceutica: null, nivel: 2, activo: true },
  { codigoAtc: 'L01CB01', dci: 'Etopósido', concentracion: '50 mg', formaFarmaceutica: 'Sólido oral', nivel: 2, activo: true },
  { codigoAtc: 'L01CD02', dci: 'Docetaxel', concentracion: '20 mg', formaFarmaceutica: 'Líquido parenteral', nivel: 2, activo: true },
  { codigoAtc: 'L01CE02', dci: 'Irinotecán', concentracion: '20 mg/mL', formaFarmaceutica: 'Líquido parenteral', nivel: 2, activo: true },
  { codigoAtc: 'L01DA01', dci: 'Dactinomicina', concentracion: '0,5 mg', formaFarmaceutica: 'Sólido parenteral', nivel: 2, activo: true },
  { codigoAtc: 'L01DB01', dci: 'Doxorubicina', concentracion: '10 mg', formaFarmaceutica: 'Sólido parenteral', nivel: 2, activo: true },
  { codigoAtc: 'L01DB02', dci: 'Daunorubicina', concentracion: '20 mg', formaFarmaceutica: 'Sólido parenteral', nivel: 2, activo: true },
  { codigoAtc: 'L01DB03', dci: 'Epirubicina parenteral', concentracion: '10 mg', formaFarmaceutica: 'Líquido', nivel: 2, activo: true },
  { codigoAtc: 'L01DB06', dci: 'Idarubicina parenteral', concentracion: '10 mg', formaFarmaceutica: 'Sólido', nivel: 2, activo: true },
  { codigoAtc: 'L01DB07', dci: 'Mitoxantrona', concentracion: '2 mg/mL', formaFarmaceutica: 'Líquido parenteral', nivel: 2, activo: true },
  { codigoAtc: 'L01DC01', dci: 'Bleomicina', concentracion: '15 UI', formaFarmaceutica: 'Sólido parenteral', nivel: 2, activo: true },
  { codigoAtc: 'L01DC03', dci: 'Mitomicina', concentracion: '20 mg', formaFarmaceutica: 'Sólido parenteral', nivel: 2, activo: true },
  { codigoAtc: 'L01EA01', dci: 'Imatinib', concentracion: '100 mg - 400 mg', formaFarmaceutica: 'Sólido oral', nivel: 3, activo: true },
  { codigoAtc: 'L01EA03', dci: 'Nilotinib', concentracion: '150 mg', formaFarmaceutica: 'Sólido oral', nivel: 2, activo: true },
  { codigoAtc: 'L01EB03', dci: 'Afatinib', concentracion: '20 mg - 50 mg', formaFarmaceutica: 'Sólido oral', nivel: 3, activo: true },
  { codigoAtc: 'L01EC01', dci: 'Vemurafenib', concentracion: '70%', formaFarmaceutica: 'Sólido oral', nivel: 3, activo: true },
  { codigoAtc: 'L01ED03', dci: 'Alectinib', concentracion: '150 mg', formaFarmaceutica: 'Sólido oral', nivel: 3, activo: true },
  { codigoAtc: 'L01EJ01', dci: 'Ruxolitinib', concentracion: '5 mg - 20 mg', formaFarmaceutica: 'Sólido oral', nivel: 3, activo: true },
  { codigoAtc: 'L01EK01', dci: 'Axitinib', concentracion: '5 mg', formaFarmaceutica: 'Sólido oral', nivel: 3, activo: true },
  { codigoAtc: 'L01EG02', dci: 'Everólimus', concentracion: '10 mg', formaFarmaceutica: 'Sólido oral', nivel: 2, activo: true },
  { codigoAtc: 'L01EL01', dci: 'Ibrutinib', concentracion: '140 mg', formaFarmaceutica: 'Sólido oral', nivel: 3, activo: true },
  { codigoAtc: 'L01EX01', dci: 'Sunitinib', concentracion: '60%', formaFarmaceutica: 'Sólido oral', nivel: 3, activo: true },
  { codigoAtc: 'L01EX02', dci: 'Sorafenib', concentracion: '200 mg', formaFarmaceutica: 'Sólido oral', nivel: 3, activo: true },
  { codigoAtc: 'L01EX08', dci: 'Lenvatinib', concentracion: '4 mg', formaFarmaceutica: 'Sólido oral', nivel: 3, activo: true },
  { codigoAtc: 'L01FA01', dci: 'Rituximab /11,7 mL', concentracion: '1400 mg', formaFarmaceutica: 'Líquido parenteral', nivel: 2, activo: true },
  { codigoAtc: 'L01FD01', dci: 'Trastuzumab', concentracion: '440 mg', formaFarmaceutica: 'Sólido parenteral', nivel: 3, activo: true },
  { codigoAtc: 'L01FD02', dci: 'Pertuzumab', concentracion: '30 mg/mL', formaFarmaceutica: 'Líquido parenteral', nivel: 3, activo: true },
  { codigoAtc: 'L01FD03', dci: 'Trastuzumab Emtansina', concentracion: '100 mg', formaFarmaceutica: 'Sólido parenteral', nivel: 3, activo: true },
  { codigoAtc: 'L01FE01', dci: 'Cetuximab', concentracion: '5 mg/mL', formaFarmaceutica: 'Líquido parenteral', nivel: 3, activo: true },
  { codigoAtc: 'L01FF02', dci: 'Pembrolizumab', concentracion: '25 mg/mL', formaFarmaceutica: 'Líquido parenteral', nivel: 3, activo: true },
  { codigoAtc: 'L01FG01', dci: 'Bevacizumab', concentracion: '25 mg/mL', formaFarmaceutica: 'Líquido parenteral', nivel: 3, activo: true },
  { codigoAtc: 'L01XA01', dci: 'Cisplatino parenteral', concentracion: '10 mg', formaFarmaceutica: 'Líquido', nivel: 2, activo: true },
  { codigoAtc: 'L01XA02', dci: 'Carboplatino parenteral', concentracion: '150 mg', formaFarmaceutica: 'Líquido', nivel: 2, activo: true },
  { codigoAtc: 'L01XA03', dci: 'Oxaliplatino parenteral', concentracion: '50 mg', formaFarmaceutica: 'Sólido', nivel: 2, activo: true },
  { codigoAtc: 'L01XB01', dci: 'Procarbazina', concentracion: '50 mg', formaFarmaceutica: 'Sólido oral', nivel: 2, activo: true },
  { codigoAtc: 'L01XG01', dci: 'Bortezomib', concentracion: '3,5 mg', formaFarmaceutica: 'Sólido parenteral', nivel: 2, activo: true },
  { codigoAtc: 'L01XK01', dci: 'Olaparib', concentracion: '50 mg - 150 mg', formaFarmaceutica: 'Sólido oral', nivel: 3, activo: true },
  { codigoAtc: 'L01XX02', dci: 'Asparaginasa', concentracion: '10.000 UI', formaFarmaceutica: 'Sólido parenteral', nivel: 2, activo: true },
  { codigoAtc: 'L01XX05', dci: 'Asparaginasa', concentracion: '500 mg', formaFarmaceutica: 'Sólido oral', nivel: 2, activo: true },
  { codigoAtc: 'L02AE02', dci: 'Leuprorelina parenteral', concentracion: '3,75 mg - 11,25 mg', formaFarmaceutica: 'Sólido', nivel: 2, activo: true },
  { codigoAtc: 'L02AE04', dci: 'Triptorelina', concentracion: '3,75 mg - 22,5 mg', formaFarmaceutica: 'Sólido parenteral', nivel: 3, activo: true },
  { codigoAtc: 'L02BA01', dci: 'Tamoxifeno', concentracion: '10 mg - 20 mg', formaFarmaceutica: 'Sólido oral', nivel: 2, activo: true },
  { codigoAtc: 'L02BA03', dci: 'Fulvestrant', concentracion: '50 mg/mL', formaFarmaceutica: 'Líquido parenteral', nivel: 2, activo: true },
  { codigoAtc: 'L02BB03', dci: 'Bicalutamida', concentracion: '50 mg', formaFarmaceutica: 'Sólido oral', nivel: 2, activo: true },
  { codigoAtc: 'L02BB04', dci: 'Enzalutamida', concentracion: '70%', formaFarmaceutica: 'Sólido oral', nivel: 2, activo: true },
  { codigoAtc: 'L02BB05', dci: 'Apalutamida', concentracion: '60 mg', formaFarmaceutica: 'Sólido oral', nivel: 2, activo: true },
  { codigoAtc: 'L02BG04', dci: 'Letrozol', concentracion: '2,5 mg', formaFarmaceutica: 'Sólido oral', nivel: 2, activo: true },
  { codigoAtc: 'L02BG06', dci: 'Exemestano', concentracion: '25 mg', formaFarmaceutica: 'Sólido oral', nivel: 3, activo: true },
  { codigoAtc: 'L03AA02', dci: 'Filgrastim', concentracion: '300 mcg', formaFarmaceutica: 'Líquido parenteral', nivel: 2, activo: true },
  { codigoAtc: 'L03AA13', dci: 'Pegfilgrastim', concentracion: '10 mg/mL', formaFarmaceutica: 'Líquido parenteral', nivel: 2, activo: true },
  { codigoAtc: 'L03AB05', dci: 'Interferón alfa 2b parenteral', concentracion: '000.000 UI', formaFarmaceutica: 'Líquido', nivel: 2, activo: true },
  { codigoAtc: 'L03AB07', dci: 'Interferón beta 1a parenteral', concentracion: '000.000 UI', formaFarmaceutica: 'Sólido', nivel: 2, activo: true },
  { codigoAtc: 'L03AB08', dci: 'TInRtAerCfTeOró An LbIMetaE N1TbARIO Y METALBíqOuLidISoM pOarenteral 8´000.000 UI', concentracion: '000.000 UI', formaFarmaceutica: null, nivel: 2, activo: true },
  { codigoAtc: 'L03AB10', dci: 'Peginterferón alfa 2b', concentracion: '100 mcg', formaFarmaceutica: 'Líquido parenteral', nivel: 2, activo: true },
  { codigoAtc: 'L03AX03', dci: 'Vacuna BCG', concentracion: null, formaFarmaceutica: 'Sólido', nivel: 2, activo: true },
  { codigoAtc: 'L04AA06', dci: 'Micofenolato', concentracion: '180 mg - 500 mg', formaFarmaceutica: 'Sólido oral', nivel: 1, activo: true },
  { codigoAtc: 'L04AA10', dci: 'Sirolimús', concentracion: '1 mg', formaFarmaceutica: 'Sólido oral', nivel: 3, activo: true },
  { codigoAtc: 'L04AA13', dci: 'Leflunomida', concentracion: '20 mg', formaFarmaceutica: 'Sólido oral', nivel: 2, activo: true },
  { codigoAtc: 'L04AA18', dci: 'Everólimus ;', concentracion: '0,50 mg', formaFarmaceutica: 'Sólido oral', nivel: 2, activo: true },
  { codigoAtc: 'L04AA33', dci: 'Vedolizumab', concentracion: '300 mg', formaFarmaceutica: 'Sólido parenteral', nivel: 3, activo: true },
  { codigoAtc: 'L04AA36', dci: 'Ocrelizumab', concentracion: '30 mg/mL', formaFarmaceutica: 'Líquido parenteral', nivel: 3, activo: true },
  { codigoAtc: 'L04AB01', dci: 'Etanercept parenteral', concentracion: '50 mg', formaFarmaceutica: 'Líquido parenteral', nivel: 2, activo: true },
  { codigoAtc: 'L04AB02', dci: 'Infliximab', concentracion: '100 mg', formaFarmaceutica: 'Sólido parenteral', nivel: 2, activo: true },
  { codigoAtc: 'L04AB04', dci: 'Adalimumab', concentracion: '40 mg', formaFarmaceutica: 'Líquido parenteral', nivel: 2, activo: true },
  { codigoAtc: 'L04AC02', dci: 'Basiliximab', concentracion: '20 mg/mL', formaFarmaceutica: 'Sólido parenteral', nivel: 3, activo: true },
  { codigoAtc: 'L04AC07', dci: 'Tocilizumab', concentracion: '162 mg', formaFarmaceutica: 'Líquido parenteral', nivel: 2, activo: true },
  { codigoAtc: 'L04AC16', dci: 'Guselkumab', concentracion: '100 mg/mL', formaFarmaceutica: 'Líquido parenteral', nivel: 2, activo: true },
  { codigoAtc: 'L04AD01', dci: 'Ciclosporina', concentracion: '50 mg/mL', formaFarmaceutica: 'Líquido parenteral', nivel: 2, activo: true },
  { codigoAtc: 'L04AD02', dci: 'Tacrólimus', concentracion: '0,5 mg/mL', formaFarmaceutica: 'Sólido oral', nivel: 2, activo: true },
  { codigoAtc: 'L04AX01', dci: 'Azatioprina', concentracion: '50 mg', formaFarmaceutica: 'Sólido oral', nivel: 2, activo: true },
  { codigoAtc: 'L04AX02', dci: 'Talidomida', concentracion: '100 mg', formaFarmaceutica: 'Sólido oral', nivel: 2, activo: true },
  { codigoAtc: 'L04AX04', dci: 'Lenalidomida', concentracion: '2,5 mg - 25 mg', formaFarmaceutica: 'Sólido oral', nivel: 3, activo: true },
  { codigoAtc: 'L04AX05', dci: 'Pirfenidona', concentracion: '200 mg - 801 mg', formaFarmaceutica: 'Sólido oral', nivel: 3, activo: true },
  { codigoAtc: 'M01AB05', dci: 'Diclofenaco', concentracion: '50 mg', formaFarmaceutica: 'Sólido oral', nivel: 1, activo: true },
  { codigoAtc: 'M01AB15', dci: 'Ketorolaco', concentracion: '30 mg/mL', formaFarmaceutica: 'Líquido parenteral', nivel: 1, activo: true },
  { codigoAtc: 'M01AE01', dci: 'Ibuprofeno', concentracion: '4 mg/mL', formaFarmaceutica: 'Líquido parenteral', nivel: 1, activo: true },
  { codigoAtc: 'M01CC01', dci: 'Penicilamina', concentracion: '125 mg', formaFarmaceutica: 'Sólido oral', nivel: 1, activo: true },
  { codigoAtc: 'M03AB01', dci: 'Suxametonio', concentracion: '20 mg/mL', formaFarmaceutica: 'Líquido parenteral', nivel: 2, activo: true },
  { codigoAtc: 'M03AC01', dci: 'Pancuronio', concentracion: '2 mg/mL', formaFarmaceutica: 'Líquido parenteral', nivel: 2, activo: true },
  { codigoAtc: 'M03AC09', dci: 'Bromuro de Rocuronio', concentracion: '10 mg/mL', formaFarmaceutica: 'Líquido parenteral', nivel: 2, activo: true },
  { codigoAtc: 'M03AX01', dci: 'Toxina botulínica 100 U', concentracion: null, formaFarmaceutica: 'Sólido parenteral', nivel: 2, activo: true },
  { codigoAtc: 'M03CA01', dci: 'Dantroleno', concentracion: '20 mg', formaFarmaceutica: 'Sólido parenteral', nivel: 2, activo: true },
  { codigoAtc: 'M04AA01', dci: 'Alopurinol', concentracion: '100 mg', formaFarmaceutica: 'Sólido oral', nivel: 1, activo: true },
  { codigoAtc: 'M04AC01', dci: 'Colchicina', concentracion: '0,5 mg', formaFarmaceutica: 'Sólido oral', nivel: 1, activo: true },
  { codigoAtc: 'M05BA08', dci: 'Ácido zoledrónico parenteral', concentracion: '4 mg', formaFarmaceutica: 'Sólido', nivel: 3, activo: true },
  { codigoAtc: 'N01AB08', dci: 'Sevoflurano para inhalación', concentracion: '1 mg/mL', formaFarmaceutica: 'Líquido', nivel: 2, activo: true },
  { codigoAtc: 'N01AF03', dci: 'Tiopental sódico', concentracion: '1 g', formaFarmaceutica: 'Sólido parenteral', nivel: 2, activo: true },
  { codigoAtc: 'N01AH01', dci: 'Fentanilo cutáneo', concentracion: '4,2 mg', formaFarmaceutica: 'Sólido', nivel: 2, activo: true },
  { codigoAtc: 'N01AH06', dci: 'Remifentanilo', concentracion: '2 mg', formaFarmaceutica: 'Sólido parenteral', nivel: 2, activo: true },
  { codigoAtc: 'N01AX10', dci: 'Propofol', concentracion: '10 mg/mL', formaFarmaceutica: 'Líquido parenteral', nivel: 2, activo: true },
  { codigoAtc: 'N01BB01', dci: 'Bupivacaína', concentracion: '0,5 %', formaFarmaceutica: 'Líquido parenteral', nivel: 2, activo: true },
  { codigoAtc: 'N01BB02', dci: 'Lidocaína cutáneo', concentracion: '5 %', formaFarmaceutica: 'Sólido', nivel: 2, activo: true },
  { codigoAtc: 'N01BB02', dci: 'Lidocaína', concentracion: '2 %', formaFarmaceutica: 'Líquido parenteral', nivel: 1, activo: true },
  { codigoAtc: 'N01BB51', dci: 'Bupivacaína hiperbárica', concentracion: '0,5 %', formaFarmaceutica: 'Líquido parenteral', nivel: 2, activo: true },
  { codigoAtc: 'N01BB52', dci: 'Lidocaína con Epinefrina + 1:80.000', concentracion: '2 %', formaFarmaceutica: 'Líquido parenteral', nivel: 1, activo: true },
  { codigoAtc: 'N02AA01', dci: 'Morfina', concentracion: '2 mg/mL', formaFarmaceutica: 'Líquido parenteral', nivel: 1, activo: true },
  { codigoAtc: 'N02AA03', dci: 'Hidromorfona', concentracion: '2,5 mg', formaFarmaceutica: 'Sólido oral', nivel: 1, activo: true },
  { codigoAtc: 'N02AA05', dci: 'Oxicodona', concentracion: '10 mg/5 mL', formaFarmaceutica: 'Líquido oral', nivel: 1, activo: true },
  { codigoAtc: 'N02AA08', dci: 'Dihidrocodeína', concentracion: '10 mg', formaFarmaceutica: 'Sólido oral', nivel: 1, activo: true },
  { codigoAtc: 'N02AE01', dci: 'Buprenorfina', concentracion: '5 mg - 20 mg', formaFarmaceutica: 'Sólido oral', nivel: 1, activo: true },
  { codigoAtc: 'N02AX02', dci: 'Tramadol', concentracion: '50 mg/mL', formaFarmaceutica: 'Líquido parenteral', nivel: 2, activo: true },
  { codigoAtc: 'N02AX06', dci: 'Tapentadol', concentracion: '50 mg', formaFarmaceutica: 'Sólido oral', nivel: 2, activo: true },
  { codigoAtc: 'N02BA01', dci: 'Ácido acetilsalicílico', concentracion: '500 mg', formaFarmaceutica: 'Sólido oral', nivel: 1, activo: true },
  { codigoAtc: 'N02BE01', dci: 'Paracetamol', concentracion: '10 mg/mL', formaFarmaceutica: 'Líquido parenteral', nivel: 1, activo: true },
  { codigoAtc: 'N03AA02', dci: 'Fenobarbital', concentracion: '60 mg/mL', formaFarmaceutica: 'Líquido parenteral', nivel: 2, activo: true },
  { codigoAtc: 'N03AB02', dci: 'Fenitoína', concentracion: '50 mg/mL', formaFarmaceutica: 'Líquido parenteral', nivel: 2, activo: true },
  { codigoAtc: 'N03AE01', dci: 'Clonazepam', concentracion: '0,5 mg - 2 mg', formaFarmaceutica: 'Sólido oral', nivel: 1, activo: true },
  { codigoAtc: 'N03AF01', dci: 'Carbamazepina', concentracion: '400 mg', formaFarmaceutica: 'Sólido oral', nivel: 1, activo: true },
  { codigoAtc: 'N03AG01', dci: 'Ácido valproico', concentracion: '200 mg/mL', formaFarmaceutica: 'Líquido oral', nivel: 1, activo: true },
  { codigoAtc: 'N03AX09', dci: 'Lamotrigina', concentracion: '25 mg - 100 mg', formaFarmaceutica: 'Sólido oral', nivel: 2, activo: true },
  { codigoAtc: 'N03AX11', dci: 'Topiramato', concentracion: '25 mg', formaFarmaceutica: 'Sólido oral', nivel: 2, activo: true },
  { codigoAtc: 'N03AX12', dci: 'Gabapentina', concentracion: '500 mg/5 mL', formaFarmaceutica: 'Líquido oral', nivel: 1, activo: true },
  { codigoAtc: 'N03AX14', dci: 'Levetiracetam', concentracion: '100 mg/mL', formaFarmaceutica: 'Líquido parenteral', nivel: 3, activo: true },
  { codigoAtc: 'N04AA02', dci: 'Biperideno', concentracion: '2 mg', formaFarmaceutica: 'Sólido oral', nivel: 2, activo: true },
  { codigoAtc: 'N04BA02', dci: 'Levodopa + Carbidopa', concentracion: '250 mg', formaFarmaceutica: 'Sólido oral', nivel: 1, activo: true },
  { codigoAtc: 'N04BC06', dci: 'Cabergolina', concentracion: '0,5 mg', formaFarmaceutica: 'Sólido oral', nivel: 2, activo: true },
  { codigoAtc: 'N04BD01', dci: 'Selegilina', concentracion: '5 mg', formaFarmaceutica: 'Sólido oral', nivel: 2, activo: true },
  { codigoAtc: 'N05AA01', dci: 'Clorpromazina', concentracion: '25 mg', formaFarmaceutica: 'Sólido oral', nivel: 2, activo: true },
  { codigoAtc: 'N05AA02', dci: 'Levomepromazina', concentracion: '25 mg/mL', formaFarmaceutica: 'Líquido parenteral', nivel: 2, activo: true },
  { codigoAtc: 'N05AD01', dci: 'Haloperidol', concentracion: '5 mg/mL', formaFarmaceutica: 'Líquido parenteral', nivel: 1, activo: true },
  { codigoAtc: 'N05AD01', dci: 'Haloperidol decanoato', concentracion: '50 mg/mL', formaFarmaceutica: 'Líquido parenteral', nivel: 2, activo: true },
  { codigoAtc: 'N05AH04', dci: 'Quetiapina', concentracion: '25 mg - 300 mg', formaFarmaceutica: 'Sólido oral', nivel: 2, activo: true },
  { codigoAtc: 'N05AN01', dci: 'Litio, carbonato', concentracion: '300 mg', formaFarmaceutica: 'Sólido oral', nivel: 2, activo: true },
  { codigoAtc: 'N05AX08', dci: 'Risperidona', concentracion: '1 mg', formaFarmaceutica: 'Sólido parenteral', nivel: 2, activo: true },
  { codigoAtc: 'N05BA01', dci: 'Diazepam', concentracion: '5 mg/mL', formaFarmaceutica: 'Líquido parenteral', nivel: 1, activo: true },
  { codigoAtc: 'N05BA06', dci: 'Lorazepam', concentracion: '1 mg', formaFarmaceutica: 'Sólido oral', nivel: 2, activo: true },
  { codigoAtc: 'N05BA09', dci: 'Clobazam', concentracion: '10 mg', formaFarmaceutica: 'Sólido oral', nivel: 2, activo: true },
  { codigoAtc: 'N05BA12', dci: 'Alprazolam', concentracion: '0,25 mg', formaFarmaceutica: 'Sólido oral', nivel: 1, activo: true },
  { codigoAtc: 'N05CC01', dci: 'Hidrato de cloral', concentracion: '100 mg/mL', formaFarmaceutica: 'Líquido oral', nivel: 2, activo: true },
  { codigoAtc: 'N05CD08', dci: 'Midazolam', concentracion: '1 mg/mL', formaFarmaceutica: 'Líquido parenteral', nivel: 2, activo: true },
  { codigoAtc: 'N05CM18', dci: 'Dexmedetomidina', concentracion: '100 mcg/mL', formaFarmaceutica: 'Líquido parenteral', nivel: 2, activo: true },
  { codigoAtc: 'N06AA09', dci: 'Amitriptilina', concentracion: '10 mg', formaFarmaceutica: 'Sólido oral', nivel: 1, activo: true },
  { codigoAtc: 'N06AB03', dci: 'Fluoxetina', concentracion: '20 mg', formaFarmaceutica: 'Sólido oral', nivel: 1, activo: true },
  { codigoAtc: 'N06AB06', dci: 'Sertralina', concentracion: '50 mg', formaFarmaceutica: 'Sólido oral', nivel: 1, activo: true },
  { codigoAtc: 'N06BC01', dci: 'Cafeína', concentracion: '20 mg/mL', formaFarmaceutica: 'Líquido parenteral', nivel: 2, activo: true },
  { codigoAtc: 'N07AA01', dci: 'Neostigmina', concentracion: '0,5 mg/mL', formaFarmaceutica: 'Líquido parenteral', nivel: 2, activo: true },
  { codigoAtc: 'N07AA02', dci: 'Piridostigmina', concentracion: '60 mg', formaFarmaceutica: 'Sólido oral', nivel: 2, activo: true },
  { codigoAtc: 'N07BB01', dci: 'Disulfiram', concentracion: '500 mg', formaFarmaceutica: 'Sólido oral', nivel: 2, activo: true },
  { codigoAtc: 'N07BC02', dci: 'Metadona', concentracion: '10 mg', formaFarmaceutica: 'Sólido oral', nivel: 1, activo: true },
  { codigoAtc: 'P01AB01', dci: 'Metronidazol', concentracion: '250 mg/5 mL', formaFarmaceutica: 'Sólido oral', nivel: 1, activo: true },
  { codigoAtc: 'P01AB02', dci: 'Tinidazol', concentracion: '150 mg', formaFarmaceutica: 'Sólido vaginal', nivel: 1, activo: true },
  { codigoAtc: 'P01BA01', dci: 'Cloroquina', concentracion: '250 mg', formaFarmaceutica: 'Sólido oral', nivel: 1, activo: true },
  { codigoAtc: 'P01BA02', dci: 'Hidroxicloroquina', concentracion: '200 mg', formaFarmaceutica: 'Sólido oral', nivel: 1, activo: true },
  { codigoAtc: 'P01BA03', dci: 'Primaquina', concentracion: '7,5 mg', formaFarmaceutica: 'Sólido oral', nivel: 1, activo: true },
  { codigoAtc: 'P01BC01', dci: 'Quinina', concentracion: '300 mg', formaFarmaceutica: 'Sólido oral', nivel: 1, activo: true },
  { codigoAtc: 'P01BD01', dci: 'Pirimetamina', concentracion: '25 mg', formaFarmaceutica: 'Sólido oral', nivel: 3, activo: true },
  { codigoAtc: 'P01BE03', dci: 'Artesunato', concentracion: '60 mg', formaFarmaceutica: 'Sólido parenteral', nivel: 2, activo: true },
  { codigoAtc: 'P01BF01', dci: 'Arteméter + Lumefantrina', concentracion: '20 mg', formaFarmaceutica: 'Sólido oral', nivel: 1, activo: true },
  { codigoAtc: 'P01CA02', dci: 'Benznidazol', concentracion: '50 mg', formaFarmaceutica: 'Sólido oral', nivel: 1, activo: true },
  { codigoAtc: 'P01CB01', dci: 'Antimoniato de meglumina', concentracion: '300 mg/mL', formaFarmaceutica: 'Líquido parenteral', nivel: 1, activo: true },
  { codigoAtc: 'P01CX04', dci: 'Miltefosina', concentracion: '10 mg', formaFarmaceutica: 'Sólido oral', nivel: 1, activo: true },
  { codigoAtc: 'P02BA01', dci: 'Praziquantel', concentracion: '600 mg', formaFarmaceutica: 'Sólido oral', nivel: 1, activo: true },
  { codigoAtc: 'P02CA03', dci: 'Albendazol', concentracion: '400 mg', formaFarmaceutica: 'Sólido oral', nivel: 1, activo: true },
  { codigoAtc: 'P02CF01', dci: 'Ivermectina', concentracion: '6 mg', formaFarmaceutica: 'Sólido oral', nivel: 1, activo: true },
  { codigoAtc: 'P03AC04', dci: 'Permetrina cutáneo', concentracion: '1 %', formaFarmaceutica: 'Líquido', nivel: 1, activo: true },
  { codigoAtc: 'R01AD09', dci: 'Mometasona', concentracion: '50 mcg', formaFarmaceutica: null, nivel: 1, activo: true },
  { codigoAtc: 'R03AA01', dci: 'para inhalación', concentracion: '22,5 mg/mL', formaFarmaceutica: 'Líquido', nivel: 1, activo: true },
  { codigoAtc: 'R03AC02', dci: 'Salbutamol inhalación/ para', concentracion: '5 mg/mL', formaFarmaceutica: 'Líquido', nivel: 1, activo: true },
  { codigoAtc: 'R03AC18', dci: 'Indacaterol', concentracion: '150 mcg', formaFarmaceutica: 'Sólido', nivel: 2, activo: true },
  { codigoAtc: 'R03AK06', dci: 'Salmeterol + Fluticasona', concentracion: '50 mcg', formaFarmaceutica: 'Sólido', nivel: 1, activo: true },
  { codigoAtc: 'R03BA01', dci: 'Beclometasona para inhalación', concentracion: '250 mcg', formaFarmaceutica: 'Líquido', nivel: 1, activo: true },
  { codigoAtc: 'R03BA05', dci: 'Fluticasona', concentracion: '125 mcg', formaFarmaceutica: 'Líquido', nivel: 1, activo: true },
  { codigoAtc: 'R03BB01', dci: 'Bromuro de ipratropio para inhalación', concentracion: '0,25 mg/mL', formaFarmaceutica: 'Líquido', nivel: 1, activo: true },
  { codigoAtc: 'R03BB04', dci: 'Bromuro de tiotropio para inhalación', concentracion: '18 mcg', formaFarmaceutica: 'Sólido', nivel: 1, activo: true },
  { codigoAtc: 'R03DA05', dci: 'Aminofilina', concentracion: '25 mg/mL', formaFarmaceutica: 'Líquido parenteral', nivel: 2, activo: true },
  { codigoAtc: 'R05CB01', dci: 'Acetilcisteína para inhalación', concentracion: '100 mg/mL', formaFarmaceutica: 'Líquido', nivel: 2, activo: true },
  { codigoAtc: 'R05CB13', dci: 'para inhalación /2,5 mL', concentracion: '2,5 mg', formaFarmaceutica: 'Líquido', nivel: 1, activo: true },
  { codigoAtc: 'R06AA02', dci: 'Difenhidramina', concentracion: '50 mg/mL', formaFarmaceutica: 'Líquido parenteral', nivel: 1, activo: true },
  { codigoAtc: 'R06AA11', dci: 'Dimenhidrinato', concentracion: '50 mg', formaFarmaceutica: 'Sólido oral', nivel: 1, activo: true },
  { codigoAtc: 'R06AX13', dci: 'Loratadina', concentracion: '10 mg', formaFarmaceutica: 'Sólido oral', nivel: 1, activo: true },
  { codigoAtc: 'R07AA02', dci: 'intratraqueal', concentracion: '25 mg/mL', formaFarmaceutica: 'Líquido', nivel: 2, activo: true },
  { codigoAtc: 'S01AA01', dci: 'Cloranfenicol Semisólido oftálmico', concentracion: '1 %', formaFarmaceutica: 'Líquido oftálmico', nivel: 1, activo: true },
  { codigoAtc: 'S01AA12', dci: 'Tobramicina Semi', concentracion: '0,3 %', formaFarmaceutica: 'sólido oftálmico', nivel: 1, activo: true },
  { codigoAtc: 'S01AA17', dci: 'Eritromicina Semi', concentracion: '0,5 %', formaFarmaceutica: 'sólido oftálmico', nivel: 1, activo: true },
  { codigoAtc: 'S01AD03', dci: 'Aciclovir Semi', concentracion: '3 %', formaFarmaceutica: 'sólido oftálmico', nivel: 2, activo: true },
  { codigoAtc: 'S01AE03', dci: 'Ciprofloxacina', concentracion: '0,3 %', formaFarmaceutica: 'Líquido oftálmico', nivel: 1, activo: true },
  { codigoAtc: 'S01BA01', dci: 'Dexametasona', concentracion: '1 mg/mL', formaFarmaceutica: 'Líquido oftálmico', nivel: 1, activo: true },
  { codigoAtc: 'S01BA04', dci: 'Prednisolona', concentracion: '0,12 %', formaFarmaceutica: 'Líquido oftálmico', nivel: 1, activo: true },
  { codigoAtc: 'S01BA07', dci: 'Fluorometolona', concentracion: '0,1 %', formaFarmaceutica: 'Líquido oftálmico', nivel: 1, activo: true },
  { codigoAtc: 'S01BC03', dci: 'Diclofenaco', concentracion: '0,1 %', formaFarmaceutica: 'Líquido oftálmico', nivel: 1, activo: true },
  { codigoAtc: 'S01CA01', dci: 'Dexametasona + Tobramicina Semi', concentracion: '0,1 % + 0,3 %', formaFarmaceutica: 'sólido oftálmico', nivel: 1, activo: true },
  { codigoAtc: 'S01EC01', dci: 'Acetazolamida', concentracion: '250 mg', formaFarmaceutica: 'Sólido oral', nivel: 2, activo: true },
  { codigoAtc: 'S01ED01', dci: 'Timolol', concentracion: '0,25 %', formaFarmaceutica: 'Líquido oftálmico', nivel: 2, activo: true },
  { codigoAtc: 'S01EE01', dci: 'Latanoprost', concentracion: '0,005 %', formaFarmaceutica: 'Líquido oftálmico', nivel: 2, activo: true },
  { codigoAtc: 'S01FA01', dci: 'Atropina', concentracion: '0,5 %', formaFarmaceutica: 'Líquido oftálmico', nivel: 2, activo: true },
  { codigoAtc: 'S01FA06', dci: 'Tropicamida', concentracion: '1 %', formaFarmaceutica: 'Líquido oftálmico', nivel: 2, activo: true },
  { codigoAtc: 'S01GX09', dci: 'Olopatadina', concentracion: '0,1 %', formaFarmaceutica: 'Líquido oftálmico', nivel: 1, activo: true },
  { codigoAtc: 'S01LA05', dci: 'Aflibercept', concentracion: '40 mg/mL', formaFarmaceutica: 'Líquido parenteral', nivel: 3, activo: true },
  { codigoAtc: 'V03AB04', dci: 'Pralidoxima', concentracion: '50 mg/mL', formaFarmaceutica: 'Líquido parenteral', nivel: 1, activo: true },
  { codigoAtc: 'V03AB09', dci: 'Dimercaprol', concentracion: '100 mg/mL', formaFarmaceutica: 'Líquido parenteral', nivel: 1, activo: true },
  { codigoAtc: 'V03AB14', dci: 'Protamina', concentracion: '10 mg/mL', formaFarmaceutica: 'Líquido parenteral', nivel: 2, activo: true },
  { codigoAtc: 'V03AB15', dci: 'Naloxona', concentracion: '0,4 mg/mL', formaFarmaceutica: 'Líquido parenteral', nivel: 1, activo: true },
  { codigoAtc: 'V03AB23', dci: 'Acetilcisteína', concentracion: '100 mg/mL', formaFarmaceutica: 'Líquido parenteral', nivel: 2, activo: true },
  { codigoAtc: 'V03AB25', dci: 'Flumazenil', concentracion: '0,1 mg/mL', formaFarmaceutica: 'Líquido parenteral', nivel: 1, activo: true },
  { codigoAtc: 'V03AB33', dci: 'Flumazenil', concentracion: '1 mg/mL', formaFarmaceutica: 'Líquido parenteral', nivel: 1, activo: true },
  { codigoAtc: 'V03AB34', dci: 'Fomepizol /mL', concentracion: '1 g', formaFarmaceutica: 'Líquido parenteral', nivel: 1, activo: true },
  { codigoAtc: 'V03AB35', dci: 'TSuRgAaCmTOm aAdLeIMx', concentracion: '100 mg/mL', formaFarmaceutica: null, nivel: 2, activo: true },
  { codigoAtc: 'V03AC03', dci: 'Deferasirox', concentracion: '125 mg - 500 mg', formaFarmaceutica: 'Sólido oral', nivel: 3, activo: true },
  { codigoAtc: 'V03AF01', dci: 'Mesna', concentracion: '100 mg/mL', formaFarmaceutica: 'Líquido parenteral', nivel: 3, activo: true },
  { codigoAtc: 'V03AF02', dci: 'Dexrazoxano', concentracion: '10 mg/mL', formaFarmaceutica: 'Líquido parenteral', nivel: 3, activo: true },
  { codigoAtc: 'V03AF03', dci: 'Folinato cálcico', concentracion: '15 mg', formaFarmaceutica: 'Sólido oral', nivel: 3, activo: true },
  { codigoAtc: 'V03AF05', dci: 'Amifostina', concentracion: '500 mg', formaFarmaceutica: 'Sólido parenteral', nivel: 3, activo: true },
]

async function main() {
  console.log('Seeding CNMB catalog (11va revisión 2022)...')

  // Clear existing and re-seed for idempotent runs
  await prisma.catalogoMedicamento.deleteMany({})

  const result = await prisma.catalogoMedicamento.createMany({
    data: CNMB_DATA,
  })

  console.log(`✓ Seeded ${result.count} medications from CNMB 11va revisión 2022`)
}

main()
  .catch((e) => { console.error(e); process.exit(1) })
  .finally(() => prisma.$disconnect())
